var languagedata = {
  "japanese": {
    "language_instruction": "りかいできる ことばを えらんで ください。",
    "reception": "うけつけ",
    "reception1": "うけつけ",
    "waiting_room": "まちあいしつ",
    "consultation_room": "しんさつしつ",
    "first_time": "はじめて ですか？",
    "yes": "はい",
    "no": "いいえ",
    "yes1": "はい",
    "no1": "いいえ",
    "self": "じぶんで にんしんけんさを しましたか（はい / いいえ）",
    "visit_reason": "きょう きた りゆうを えらんで ください。",
    "absence_period": "せいりが とまった",
    "nausea": "はきけ",
    "possible_pregnancy": "にんしん かもしれない",
    "inconsistent_period": "せいりが きそくてきに こない",
    "period_pain": "せいりの とき おなかが いたい",
    "itching": "いんぶが かゆい",
    "stomach_pain": "おなかが いたい",
    "infertility_question": "ふにんについて ききたい",
    "other": "そのほか",
    "question": "もんしんひょう",
    "fill_form_waiting_room": "まちあいしつで もんしんひょうを かいて ください。",
    "finished_filling_form": "かきおわったら もってきて ください。",
    "take_weight": "しんさつまでに、たいじゅう・けつあつ・にょうけんさを して ください。",
    "weit_here": "しんさつまで、きめられた ばしょで まって ください。",
    "staff_notification": "どこへ いくかは しょくいんが あんないします。",
    "call_order": "なまえ（ばんごう）の はやい人から よびます。",
    "call_order2": "じょうきょうに よって じゅんばんが かわることが あります。",
    "medicines": "くすり",
    "give_medicines_in_hospital": "くすりは しんさつのあと びょういんの中で わたします。",
    "give_medicines_out_of_hospital": "びょういんの外の やっきょくで かって もらうことが あります。",
    "prescription_validity": "しょほうせんは、出した日を ふくめて 4日間 つかえます。",
    "payment_instructions_machine": "おかねは じどうせいさんきで はらって ください。",
    "payment_instructions_cashier": "おかねは かいけいまどぐちで はらって ください。",
    "card": "しんさつけんを わたします。つぎから 見せて ください。",
    "system_information_detail": "せいどの くわしい じょうほう",
    "system_information_detail_link": "せいどの くわしい じょうほうを 見る",
    "notify_pregnancy_office": "すんでいる まちの やくしょで、にんしんの とどけでを かくにんして ください。",
    "mother_child_handbook": "母子健康手帳を もらいましょう。",
    "checkup_tickets": "妊婦健診の 受診票・補助券の 使い方を かくにんして ください。",
    "hospital_reservation": "出産する 病院や クリニックは はやめに 決めて 予約して ください。",
    "insurance_payment": "健康保険や 出産費用の はらい方を かくにんして ください。",
    "financial_support": "出産育児一時金など お金の 支援制度を かくにんして ください。",
    "municipal_support": "自治体の 相談窓口や 支援制度を 使えます。",
    "interpreter_support": "通訳や 多言語相談が 必要なときは 相談して ください。",
    "emergency_contact_info": "夜や 休みの日の 連絡先を かくにんして おきましょう。",
    "bring_documents": "受診のときに 必要な 書類や 持ち物を かくにんして ください。"
  },
  "english": {
    "language_instruction": "Please choose the language you can understand.",
    "reception": "Reception",
    "reception1": "Reception",
    "waiting_room": "Waiting room",
    "consultation_room": "Consultation room",
    "first_time": "Is this your first visit?",
    "yes": "Yes",
    "no": "No",
    "yes1": "Yes",
    "no1": "No",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Please choose the reason for today’s visit.",
    "absence_period": "My period has stopped",
    "nausea": "Nausea",
    "possible_pregnancy": "I may be pregnant",
    "inconsistent_period": "My periods are irregular",
    "period_pain": "I have stomach pain during my period",
    "itching": "Itching around the vulva",
    "stomach_pain": "Stomach pain",
    "infertility_question": "I want to ask about infertility",
    "other": "Other",
    "question": "Medical questionnaire",
    "fill_form_waiting_room": "Please fill out the medical questionnaire in the waiting room.",
    "finished_filling_form": "Please bring it to us when you have finished filling it out.",
    "take_weight": "Before your examination, please measure your weight and blood pressure and provide a urine sample.",
    "weit_here": "Please wait in the designated area until your examination.",
    "staff_notification": "A staff member will guide you where to go.",
    "call_order": "We will call patients in order by name or number.",
    "call_order2": "The order may change depending on the situation.",
    "medicines": "Medicines",
    "give_medicines_in_hospital": "Your medicines will be given inside the hospital after the examination.",
    "give_medicines_out_of_hospital": "You may need to buy your medicines at a pharmacy outside the hospital.",
    "prescription_validity": "The prescription is valid for 4 days, including the date of issue.",
    "payment_instructions_machine": "Please pay at the automated payment machine.",
    "payment_instructions_cashier": "Please pay at the cashier counter.",
    "card": "We will give you a patient registration card. Please show it from your next visit.",
    "system_information_detail": "Detailed system information",
    "system_information_detail_link": "Open detailed system information",
    "notify_pregnancy_office": "Please confirm pregnancy notification procedures at your local municipal office.",
    "mother_child_handbook": "Please receive your Maternal and Child Health Handbook.",
    "checkup_tickets": "Please confirm how to use prenatal checkup tickets and subsidy coupons.",
    "hospital_reservation": "Please decide on your delivery hospital or clinic early and make a reservation.",
    "insurance_payment": "Please confirm your health insurance and how delivery costs will be paid.",
    "financial_support": "Please confirm financial support systems such as the childbirth and childcare lump-sum allowance.",
    "municipal_support": "You can use municipal consultation services and support programs.",
    "interpreter_support": "Please ask if you need an interpreter or multilingual consultation.",
    "emergency_contact_info": "Please make sure you know the contact number for nights and holidays.",
    "bring_documents": "Please confirm the documents and items you need to bring for visits."
  },
  "chinese": {
    "language_instruction": "请选择您能理解的语言。",
    "reception": "接待",
    "reception1": "接待",
    "waiting_room": "候诊室",
    "consultation_room": "诊室",
    "first_time": "这是您第一次来吗？",
    "yes": "是",
    "no": "否",
    "yes1": "是",
    "no1": "否",
    "self": "您是否自己做过怀孕测试？是 / 否",
    "visit_reason": "请选择今天就诊的原因。",
    "absence_period": "月经停止",
    "nausea": "恶心",
    "possible_pregnancy": "可能怀孕",
    "inconsistent_period": "月经不规律",
    "period_pain": "月经时肚子痛",
    "itching": "外阴部瘙痒",
    "stomach_pain": "肚子痛",
    "infertility_question": "想咨询不孕问题",
    "other": "其他",
    "question": "问诊表",
    "fill_form_waiting_room": "请在候诊室填写问诊表。",
    "finished_filling_form": "填写完后请拿过来。",
    "take_weight": "请在诊察前测量体重、血压并进行尿检。",
    "weit_here": "请在指定地点等候诊察。",
    "staff_notification": "工作人员会 告知您去哪里。",
    "call_order": "我们会按姓名（号码）顺序叫号。",
    "call_order2": "根据情况，顺序可能会前后调整。",
    "medicines": "药",
    "give_medicines_in_hospital": "药将在诊察后在医院内交给您。",
    "give_medicines_out_of_hospital": "有时需要您到院外药局购买。",
    "prescription_validity": "处方笺有效期为包括开具当天在内的4天。",
    "payment_instructions_machine": "请在自动结算机付款。",
    "payment_instructions_cashier": "请在会计窗口付款。",
    "card": "我们会给您诊察券。下次起请出示。",
    "system_information_detail": "制度信息详情",
    "system_information_detail_link": "查看制度信息详情",
    "notify_pregnancy_office": "请在您居住的自治体确认怀孕申报手续。",
    "mother_child_handbook": "请领取母子健康手册。",
    "checkup_tickets": "请确认孕妇健诊受诊票和补助券的使用方法。",
    "hospital_reservation": "请尽早决定并预约分娩医院或诊所。",
    "insurance_payment": "请确认健康保险和分娩费用的支付方法。",
    "financial_support": "请确认出产育儿一时金等费用支援制度。",
    "municipal_support": "可以使用自治体的咨询窗口和支援制度。",
    "interpreter_support": "需要口译或多语言咨询时请提出。",
    "emergency_contact_info": "请提前确认夜间和节假日的联系方式。",
    "bring_documents": "请确认就诊时需要的文件和携带物品。"
  },
  "french": {
    "language_instruction": "Veuillez choisir la langue que vous comprenez.",
    "reception": "Accueil",
    "reception1": "Accueil",
    "waiting_room": "Salle d’attente",
    "consultation_room": "Salle de consultation",
    "first_time": "Est-ce votre première visite ?",
    "yes": "Oui",
    "no": "Non",
    "yes1": "Oui",
    "no1": "Non",
    "self": "Avez-vous fait un test de grossesse vous-même ? Oui / Non",
    "visit_reason": "Veuillez choisir le motif de votre visite aujourd’hui.",
    "absence_period": "Les règles se sont arrêtées",
    "nausea": "Nausées",
    "possible_pregnancy": "Possibilité de grossesse",
    "inconsistent_period": "Règles irrégulières",
    "period_pain": "Douleur au ventre pendant les règles",
    "itching": "Démangeaisons de la vulve",
    "stomach_pain": "Mal au ventre",
    "infertility_question": "Je veux poser des questions sur l’infertilité",
    "other": "Autre",
    "question": "Questionnaire médical",
    "fill_form_waiting_room": "Veuillez remplir le questionnaire médical dans la salle d’attente.",
    "finished_filling_form": "Quand vous avez fini de le remplir, veuillez l’apporter.",
    "take_weight": "Avant la consultation, veuillez mesurer votre poids et votre tension, et faire un test d’urine.",
    "weit_here": "Veuillez attendre à l’endroit indiqué jusqu’à la consultation.",
    "staff_notification": "Un membre du personnel vous indiquera où aller.",
    "call_order": "Nous appellerons dans l’ordre du nom ou du numéro.",
    "call_order2": "L’ordre peut changer selon la situation.",
    "medicines": "Médicaments",
    "give_medicines_in_hospital": "Les médicaments seront remis à l’hôpital après la consultation.",
    "give_medicines_out_of_hospital": "Il peut être nécessaire de les acheter dans une pharmacie extérieure.",
    "prescription_validity": "L’ordonnance est valable 4 jours, y compris le jour d’émission.",
    "payment_instructions_machine": "Veuillez payer à la machine de paiement automatique.",
    "payment_instructions_cashier": "Veuillez payer au guichet de caisse.",
    "card": "Nous vous remettrons une carte de consultation. Veuillez la présenter à partir de la prochaine visite.",
    "system_information_detail": "Détails des systèmes d’aide",
    "system_information_detail_link": "Voir les détails des systèmes d’aide",
    "notify_pregnancy_office": "Veuillez confirmer la déclaration de grossesse auprès de votre municipalité.",
    "mother_child_handbook": "Veuillez recevoir votre carnet de santé mère-enfant.",
    "checkup_tickets": "Veuillez vérifier comment utiliser les tickets de consultation prénatale et les coupons de subvention.",
    "hospital_reservation": "Veuillez choisir tôt l’hôpital ou la clinique d’accouchement et faire une réservation.",
    "insurance_payment": "Veuillez vérifier votre assurance maladie et le mode de paiement des frais d’accouchement.",
    "financial_support": "Veuillez vérifier les aides financières comme l’allocation forfaitaire de naissance et de garde d’enfant.",
    "municipal_support": "Vous pouvez utiliser les services de consultation et les programmes d’aide de la municipalité.",
    "interpreter_support": "Veuillez consulter si vous avez besoin d’un interprète ou d’une consultation multilingue.",
    "emergency_contact_info": "Veuillez vérifier les contacts pour la nuit et les jours fériés.",
    "bring_documents": "Veuillez vérifier les documents et objets à apporter lors des visites."
  },
  "korean": {
    "language_instruction": "이해할 수 있는 언어를 선택해 주세요.",
    "reception": "접수",
    "reception1": "접수",
    "waiting_room": "대기실",
    "consultation_room": "진료실",
    "first_time": "처음 방문하셨나요?",
    "yes": "네",
    "no": "아니요",
    "yes1": "네",
    "no1": "아니요",
    "self": "임신 검사를 직접 했습니까? 예 / 아니요",
    "visit_reason": "오늘 진료를 받으러 온 이유를 선택해 주세요.",
    "absence_period": "생리가 멈춤",
    "nausea": "메스꺼움",
    "possible_pregnancy": "임신일지도 모름",
    "inconsistent_period": "생리가 규칙적이지 않음",
    "period_pain": "생리 때 배가 아픔",
    "itching": "외음부가 가려움",
    "stomach_pain": "배가 아픔",
    "infertility_question": "불임에 대해 묻고 싶음",
    "other": "기타",
    "question": "문진표",
    "fill_form_waiting_room": "대기실에서 문진표를 작성해 주세요.",
    "finished_filling_form": "작성이 끝나면 가져와 주세요.",
    "take_weight": "진찰 전까지 체중, 혈압, 소변 검사를 해 주세요.",
    "weit_here": "진찰 전까지 지정된 장소에서 기다려 주세요.",
    "staff_notification": "어디로 가야 하는지는 직원이 안내합니다.",
    "call_order": "이름(번호) 순서가 빠른 분부터 부릅니다.",
    "call_order2": "상황에 따라 순서가 바뀔 수 있습니다.",
    "medicines": "약",
    "give_medicines_in_hospital": "약은 진찰 후 병원 안에서 드립니다.",
    "give_medicines_out_of_hospital": "병원 밖 약국에서 구입해야 하는 경우가 있습니다.",
    "prescription_validity": "처방전은 발행일을 포함하여 4일간 유효합니다.",
    "payment_instructions_machine": "계산은 자동 정산기에서 해 주세요.",
    "payment_instructions_cashier": "계산은 회계 창구에서 해 주세요.",
    "card": "진찰권을 드립니다. 다음부터 제시해 주세요.",
    "system_information_detail": "제도 정보 상세",
    "system_information_detail_link": "제도 정보 상세 보기",
    "notify_pregnancy_office": "거주하는 지자체에서 임신 신고 절차를 확인해 주세요.",
    "mother_child_handbook": "모자건강수첩을 받으세요.",
    "checkup_tickets": "임산부 건강검진 수진표와 보조권 사용 방법을 확인해 주세요.",
    "hospital_reservation": "출산할 병원이나 클리닉은 빨리 정하고 예약해 주세요.",
    "insurance_payment": "건강보험과 출산 비용 결제 방법을 확인해 주세요.",
    "financial_support": "출산육아일시금 등 비용 지원 제도를 확인해 주세요.",
    "municipal_support": "지자체 상담 창구와 지원 제도를 이용할 수 있습니다.",
    "interpreter_support": "통역이나 다국어 상담이 필요할 때는 상담해 주세요.",
    "emergency_contact_info": "야간 및 휴일 연락처를 확인해 두세요.",
    "bring_documents": "진료 시 필요한 서류와 준비물을 확인해 주세요."
  },
  "portuguese": {
    "language_instruction": "Por favor, escolha o idioma que entende.",
    "reception": "Recepção",
    "reception1": "Recepção",
    "waiting_room": "Waiting room",
    "consultation_room": "Consultation room",
    "first_time": "É a sua primeira visita?",
    "yes": "Sim",
    "no": "Não",
    "yes1": "Sim",
    "no1": "Não",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Escolha o motivo da sua visita hoje.",
    "absence_period": "A menstruação parou",
    "nausea": "Náusea",
    "possible_pregnancy": "Posso estar grávida",
    "inconsistent_period": "A menstruação é irregular",
    "period_pain": "Dor abdominal durante a menstruação",
    "itching": "Coceira na vulva",
    "stomach_pain": "Dor abdominal",
    "infertility_question": "Quero perguntar sobre infertilidade",
    "other": "Outros",
    "question": "Questionário médico",
    "fill_form_waiting_room": "Preencha o questionário médico na sala de espera.",
    "finished_filling_form": "Quando terminar, traga-o para nós.",
    "take_weight": "Antes da consulta, meça o peso e a pressão arterial e faça o exame de urina.",
    "weit_here": "Aguarde no local indicado até a consulta.",
    "staff_notification": "Um funcionário indicará para onde ir.",
    "call_order": "Chamaremos por nome ou número em ordem.",
    "call_order2": "A ordem pode mudar conforme a situação.",
    "medicines": "Medicamentos",
    "give_medicines_in_hospital": "Os medicamentos serão entregues dentro do hospital após a consulta.",
    "give_medicines_out_of_hospital": "Pode ser necessário comprar os medicamentos em uma farmácia fora do hospital.",
    "prescription_validity": "A receita é válida por 4 dias, incluindo a data de emissão.",
    "payment_instructions_machine": "Pague na máquina de pagamento automático.",
    "payment_instructions_cashier": "Pague no caixa.",
    "card": "Entregaremos um cartão de consulta. Apresente-o nas próximas visitas.",
    "system_information_detail": "Informações detalhadas do sistema",
    "system_information_detail_link": "Ver informações detalhadas do sistema",
    "notify_pregnancy_office": "Confirme a notificação da gravidez na prefeitura do município onde mora.",
    "mother_child_handbook": "Receba a Caderneta de Saúde Materno-Infantil.",
    "checkup_tickets": "Confirme como usar os vouchers e cupons de apoio para consultas pré-natais.",
    "hospital_reservation": "Escolha cedo o hospital ou clínica para o parto e faça a reserva.",
    "insurance_payment": "Confirme o seguro de saúde e a forma de pagamento dos custos do parto.",
    "financial_support": "Confirme apoios financeiros, como o subsídio único de parto e cuidados infantis.",
    "municipal_support": "Você pode usar balcões de consulta e sistemas de apoio do município.",
    "interpreter_support": "Consulte-nos se precisar de intérprete ou atendimento multilíngue.",
    "emergency_contact_info": "Confirme os contatos para noites e feriados.",
    "bring_documents": "Confirme os documentos e itens necessários para a consulta."
  },
  "filipino": {
    "language_instruction": "Piliin ang wikang naiintindihan mo.",
    "reception": "Reception",
    "reception1": "Reception",
    "waiting_room": "Waiting room",
    "consultation_room": "Consultation room",
    "first_time": "Ito ba ang unang pagbisita mo?",
    "yes": "Oo",
    "no": "Hindi",
    "yes1": "Oo",
    "no1": "Hindi",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Piliin ang dahilan ng pagpunta mo ngayon.",
    "absence_period": "Tumigil ang regla",
    "nausea": "Pagduduwal",
    "possible_pregnancy": "Maaaring buntis",
    "inconsistent_period": "Hindi regular ang regla",
    "period_pain": "Sumasakit ang tiyan kapag may regla",
    "itching": "Nangangati ang panlabas na ari",
    "stomach_pain": "Masakit ang tiyan",
    "infertility_question": "Gustong magtanong tungkol sa pagkabaog",
    "other": "Iba pa",
    "question": "Medikal na questionnaire",
    "fill_form_waiting_room": "Pakisagutan ang medical questionnaire sa waiting room.",
    "finished_filling_form": "Kapag natapos mo na, pakidala ito sa amin.",
    "take_weight": "Bago ang pagsusuri, pakisukat ang timbang, presyon ng dugo, at magbigay ng ihi.",
    "weit_here": "Pakihintay sa itinakdang lugar hanggang sa pagsusuri.",
    "staff_notification": "Sasabihin ng staff kung saan ka pupunta.",
    "call_order": "Tatawag kami ayon sa pangalan o numero.",
    "call_order2": "Maaaring magbago ang pagkakasunod-sunod depende sa sitwasyon.",
    "medicines": "Mga gamot",
    "give_medicines_in_hospital": "Ibibigay ang gamot sa loob ng ospital pagkatapos ng pagsusuri.",
    "give_medicines_out_of_hospital": "Maaaring kailangan bilhin ang gamot sa botika sa labas ng ospital.",
    "prescription_validity": "Ang reseta ay may bisa sa loob ng 4 na araw kasama ang araw ng pagbigay.",
    "payment_instructions_machine": "Magbayad sa automated payment machine.",
    "payment_instructions_cashier": "Magbayad sa cashier counter.",
    "card": "Bibigyan ka namin ng patient card. Ipakita ito sa susunod na pagbisita.",
    "system_information_detail": "Detalye ng impormasyon ng sistema",
    "system_information_detail_link": "Tingnan ang detalye ng impormasyon ng sistema",
    "notify_pregnancy_office": "Pakikumpirma ang pag-uulat ng pagbubuntis sa munisipyo kung saan ka nakatira.",
    "mother_child_handbook": "Kunin ang Maternal and Child Health Handbook.",
    "checkup_tickets": "Pakikumpirma kung paano gamitin ang prenatal checkup tickets at subsidy coupons.",
    "hospital_reservation": "Magpasya at magpareserba nang maaga sa ospital o klinika kung saan manganganak.",
    "insurance_payment": "Pakikumpirma ang health insurance at paraan ng pagbabayad ng gastos sa panganganak.",
    "financial_support": "Pakikumpirma ang mga tulong-pinansyal tulad ng childbirth allowance.",
    "municipal_support": "Maaari mong gamitin ang consultation desk at support programs ng munisipyo.",
    "interpreter_support": "Magsabi kung kailangan mo ng interpreter o multilingual consultation.",
    "emergency_contact_info": "Pakikumpirma ang contact number para sa gabi at holidays.",
    "bring_documents": "Pakikumpirma ang mga dokumento at gamit na kailangan dalhin sa pagbisita."
  },
  "vietnamese": {
    "language_instruction": "Vui lòng chọn ngôn ngữ bạn hiểu.",
    "reception": "Tiếp nhận",
    "reception1": "Tiếp nhận",
    "waiting_room": "Phòng chờ",
    "consultation_room": "Phòng khám",
    "first_time": "Đây có phải lần đầu bạn đến không?",
    "yes": "Có",
    "no": "Không",
    "yes1": "Có",
    "no1": "Không",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Vui lòng chọn lý do đến khám hôm nay.",
    "absence_period": "Đã ngừng kinh nguyệt",
    "nausea": "Buồn nôn",
    "possible_pregnancy": "Có thể đang mang thai",
    "inconsistent_period": "Kinh nguyệt không đều",
    "period_pain": "Đau bụng khi có kinh",
    "itching": "Ngứa vùng âm hộ",
    "stomach_pain": "Đau bụng",
    "infertility_question": "Muốn hỏi về vô sinh",
    "other": "Khác",
    "question": "Phiếu hỏi y tế",
    "fill_form_waiting_room": "Vui lòng điền phiếu hỏi y tế tại phòng chờ.",
    "finished_filling_form": "Khi điền xong, vui lòng mang lại cho chúng tôi.",
    "take_weight": "Trước khi khám, vui lòng đo cân nặng, huyết áp và làm xét nghiệm nước tiểu.",
    "weit_here": "Vui lòng chờ tại nơi được chỉ định cho đến khi khám.",
    "staff_notification": "Nhân viên sẽ hướng dẫn bạn đi đâu.",
    "call_order": "Chúng tôi sẽ gọi theo thứ tự tên hoặc số.",
    "call_order2": "Thứ tự có thể thay đổi tùy tình hình.",
    "medicines": "Thuốc",
    "give_medicines_in_hospital": "Thuốc sẽ được phát trong bệnh viện sau khi khám.",
    "give_medicines_out_of_hospital": "Có trường hợp bạn cần mua thuốc tại nhà thuốc ngoài bệnh viện.",
    "prescription_validity": "Đơn thuốc có hiệu lực 4 ngày, bao gồm ngày phát hành.",
    "payment_instructions_machine": "Vui lòng thanh toán tại máy thanh toán tự động.",
    "payment_instructions_cashier": "Vui lòng thanh toán tại quầy thu ngân.",
    "card": "Chúng tôi sẽ đưa thẻ khám. Từ lần sau vui lòng xuất trình thẻ.",
    "system_information_detail": "Chi tiết thông tin chế độ",
    "system_information_detail_link": "Xem chi tiết thông tin chế độ",
    "notify_pregnancy_office": "Vui lòng xác nhận thủ tục khai báo mang thai tại chính quyền địa phương nơi bạn sống.",
    "mother_child_handbook": "Hãy nhận Sổ tay sức khỏe mẹ và bé.",
    "checkup_tickets": "Vui lòng xác nhận cách dùng phiếu khám thai và phiếu trợ cấp.",
    "hospital_reservation": "Hãy quyết định sớm bệnh viện hoặc phòng khám sinh con và đặt lịch.",
    "insurance_payment": "Vui lòng xác nhận bảo hiểm y tế và cách thanh toán chi phí sinh con.",
    "financial_support": "Vui lòng xác nhận các chế độ hỗ trợ chi phí như trợ cấp một lần khi sinh con.",
    "municipal_support": "Bạn có thể sử dụng quầy tư vấn và chế độ hỗ trợ của địa phương.",
    "interpreter_support": "Vui lòng hỏi nếu cần phiên dịch hoặc tư vấn đa ngôn ngữ.",
    "emergency_contact_info": "Hãy xác nhận trước số liên lạc ban đêm và ngày nghỉ.",
    "bring_documents": "Vui lòng xác nhận giấy tờ và đồ cần mang khi đi khám."
  },
  "thai": {
    "language_instruction": "กรุณาเลือกภาษาที่คุณเข้าใจ",
    "reception": "แผนกต้อนรับ",
    "reception1": "แผนกต้อนรับ",
    "waiting_room": "ห้องรอ",
    "consultation_room": "ห้องตรวจ",
    "first_time": "มาครั้งแรกใช่ไหม?",
    "yes": "ใช่",
    "no": "ไม่ใช่",
    "yes1": "ใช่",
    "no1": "ไม่ใช่",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "กรุณาเลือกเหตุผลที่มาพบแพทย์วันนี้",
    "absence_period": "ประจำเดือนหยุด",
    "nausea": "คลื่นไส้",
    "possible_pregnancy": "อาจตั้งครรภ์",
    "inconsistent_period": "ประจำเดือนไม่สม่ำเสมอ",
    "period_pain": "ปวดท้องตอนมีประจำเดือน",
    "itching": "คันบริเวณอวัยวะเพศภายนอก",
    "stomach_pain": "ปวดท้อง",
    "infertility_question": "ต้องการสอบถามเรื่องภาวะมีบุตรยาก",
    "other": "อื่น ๆ",
    "question": "แบบสอบถามทางการแพทย์",
    "fill_form_waiting_room": "กรุณากรอกแบบสอบถามทางการแพทย์ในห้องรอ",
    "finished_filling_form": "เมื่อกรอกเสร็จแล้ว กรุณานำมาให้เรา",
    "take_weight": "ก่อนตรวจ กรุณาวัดน้ำหนัก ความดันโลหิต และตรวจปัสสาวะ",
    "weit_here": "กรุณารอในสถานที่ที่กำหนดจนกว่าจะตรวจ",
    "staff_notification": "เจ้าหน้าที่จะแนะนำว่าต้องไปที่ไหน",
    "call_order": "เราจะเรียกตามลำดับชื่อหรือหมายเลข",
    "call_order2": "ลำดับอาจเปลี่ยนแปลงได้ตามสถานการณ์",
    "medicines": "ยา",
    "give_medicines_in_hospital": "จะรับยาในโรงพยาบาลหลังการตรวจ",
    "give_medicines_out_of_hospital": "บางกรณีต้องซื้อยาที่ร้านขายยานอกโรงพยาบาล",
    "prescription_validity": "ใบสั่งยามีอายุ 4 วันรวมวันที่ออกใบสั่งยา",
    "payment_instructions_machine": "กรุณาชำระเงินที่เครื่องชำระเงินอัตโนมัติ",
    "payment_instructions_cashier": "กรุณาชำระเงินที่ช่องชำระเงิน",
    "card": "เราจะมอบบัตรผู้ป่วยให้ กรุณาแสดงตั้งแต่ครั้งหน้า",
    "system_information_detail": "รายละเอียดข้อมูลระบบ",
    "system_information_detail_link": "ดูรายละเอียดข้อมูลระบบ",
    "notify_pregnancy_office": "กรุณาตรวจสอบการแจ้งการตั้งครรภ์กับเทศบาลที่คุณอาศัยอยู่",
    "mother_child_handbook": "กรุณารับสมุดสุขภาพแม่และเด็ก",
    "checkup_tickets": "กรุณาตรวจสอบวิธีใช้บัตรตรวจครรภ์และคูปองช่วยเหลือ",
    "hospital_reservation": "กรุณาตัดสินใจและจองโรงพยาบาลหรือคลินิกสำหรับคลอดแต่เนิ่น ๆ",
    "insurance_payment": "กรุณาตรวจสอบประกันสุขภาพและวิธีชำระค่าใช้จ่ายการคลอด",
    "financial_support": "กรุณาตรวจสอบระบบช่วยเหลือค่าใช้จ่าย เช่น เงินช่วยเหลือคลอดบุตร",
    "municipal_support": "คุณสามารถใช้ช่องทางปรึกษาและระบบสนับสนุนของเทศบาลได้",
    "interpreter_support": "กรุณาปรึกษาหากต้องการล่ามหรือการปรึกษาหลายภาษา",
    "emergency_contact_info": "กรุณาตรวจสอบเบอร์ติดต่อเวลากลางคืนและวันหยุด",
    "bring_documents": "กรุณาตรวจสอบเอกสารและสิ่งของที่ต้องนำมาเมื่อมารับการตรวจ"
  },
  "german": {
    "language_instruction": "Bitte wählen Sie die Sprache, die Sie verstehen.",
    "reception": "Rezeption",
    "reception1": "Rezeption",
    "waiting_room": "Wartezimmer",
    "consultation_room": "Untersuchungszimmer",
    "first_time": "Ist dies Ihr erster Besuch?",
    "yes": "Ja",
    "no": "Nein",
    "yes1": "Ja",
    "no1": "Nein",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Bitte wählen Sie den Grund Ihres heutigen Besuchs.",
    "absence_period": "Die Monatsblutung ist ausgeblieben",
    "nausea": "Übelkeit",
    "possible_pregnancy": "Ich könnte schwanger sein",
    "inconsistent_period": "Meine Periode ist unregelmäßig",
    "period_pain": "Bauchschmerzen während der Periode",
    "itching": "Juckreiz im äußeren Genitalbereich",
    "stomach_pain": "Bauchschmerzen",
    "infertility_question": "Ich möchte wegen Unfruchtbarkeit fragen",
    "other": "Sonstiges",
    "question": "Medizinischer Fragebogen",
    "fill_form_waiting_room": "Bitte füllen Sie den medizinischen Fragebogen im Wartezimmer aus.",
    "finished_filling_form": "Bitte bringen Sie ihn nach dem Ausfüllen mit.",
    "take_weight": "Bitte messen Sie vor der Untersuchung Gewicht und Blutdruck und geben Sie eine Urinprobe ab.",
    "weit_here": "Bitte warten Sie bis zur Untersuchung am angegebenen Ort.",
    "staff_notification": "Das Personal zeigt Ihnen, wohin Sie gehen sollen.",
    "call_order": "Wir rufen nach Name oder Nummer der Reihenfolge nach auf.",
    "call_order2": "Die Reihenfolge kann sich je nach Situation ändern.",
    "medicines": "Medikamente",
    "give_medicines_in_hospital": "Die Medikamente erhalten Sie nach der Untersuchung im Krankenhaus.",
    "give_medicines_out_of_hospital": "Möglicherweise müssen Sie die Medikamente in einer Apotheke außerhalb des Krankenhauses kaufen.",
    "prescription_validity": "Das Rezept ist einschließlich Ausstellungsdatum 4 Tage gültig.",
    "payment_instructions_machine": "Bitte zahlen Sie am Zahlungsautomaten.",
    "payment_instructions_cashier": "Bitte zahlen Sie am Kassenschalter.",
    "card": "Wir geben Ihnen eine Patientenkarte. Bitte zeigen Sie sie ab dem nächsten Besuch vor.",
    "system_information_detail": "Ausführliche Informationen zu Unterstützungssystemen",
    "system_information_detail_link": "Ausführliche Informationen anzeigen",
    "notify_pregnancy_office": "Bitte bestätigen Sie die Schwangerschaftsmeldung bei Ihrer Gemeinde.",
    "mother_child_handbook": "Bitte holen Sie den Mutter-Kind-Gesundheitspass ab.",
    "checkup_tickets": "Bitte prüfen Sie, wie Sie die Vorsorge-Tickets und Zuschussgutscheine verwenden.",
    "hospital_reservation": "Bitte entscheiden Sie früh über Krankenhaus oder Klinik für die Geburt und reservieren Sie.",
    "insurance_payment": "Bitte prüfen Sie Krankenversicherung und Zahlungsweise der Geburtskosten.",
    "financial_support": "Bitte prüfen Sie finanzielle Hilfen wie die Pauschale für Geburt und Kinderbetreuung.",
    "municipal_support": "Sie können Beratungsstellen und Unterstützungsprogramme der Gemeinde nutzen.",
    "interpreter_support": "Bitte fragen Sie, wenn Sie Dolmetschen oder mehrsprachige Beratung benötigen.",
    "emergency_contact_info": "Bitte prüfen Sie die Kontaktstellen für Nachtzeiten und Feiertage.",
    "bring_documents": "Bitte prüfen Sie die Unterlagen und Dinge, die Sie zum Besuch mitbringen müssen."
  },
  "indonesian": {
    "language_instruction": "Silakan pilih bahasa yang Anda pahami.",
    "reception": "Pendaftaran",
    "reception1": "Pendaftaran",
    "waiting_room": "Ruang tunggu",
    "consultation_room": "Ruang konsultasi",
    "first_time": "Apakah ini kunjungan pertama Anda?",
    "yes": "Ya",
    "no": "Tidak",
    "yes1": "Ya",
    "no1": "Tidak",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Silakan pilih alasan kunjungan Anda hari ini.",
    "absence_period": "Menstruasi berhenti",
    "nausea": "Mual",
    "possible_pregnancy": "Mungkin hamil",
    "inconsistent_period": "Menstruasi tidak teratur",
    "period_pain": "Sakit perut saat menstruasi",
    "itching": "Gatal pada vulva",
    "stomach_pain": "Sakit perut",
    "infertility_question": "Ingin bertanya tentang infertilitas",
    "other": "Lainnya",
    "question": "Kuesioner medis",
    "fill_form_waiting_room": "Silakan isi kuesioner medis di ruang tunggu.",
    "finished_filling_form": "Setelah selesai mengisi, silakan bawa kepada kami.",
    "take_weight": "Sebelum pemeriksaan, ukur berat badan dan tekanan darah, serta lakukan tes urine.",
    "weit_here": "Silakan tunggu di tempat yang ditentukan sampai pemeriksaan.",
    "staff_notification": "Staf akan memberi tahu ke mana Anda harus pergi.",
    "call_order": "Kami akan memanggil sesuai urutan nama atau nomor.",
    "call_order2": "Urutan dapat berubah tergantung situasi.",
    "medicines": "Obat",
    "give_medicines_in_hospital": "Obat akan diberikan di dalam rumah sakit setelah pemeriksaan.",
    "give_medicines_out_of_hospital": "Anda mungkin perlu membeli obat di apotek luar rumah sakit.",
    "prescription_validity": "Resep berlaku 4 hari termasuk tanggal penerbitan.",
    "payment_instructions_machine": "Silakan bayar di mesin pembayaran otomatis.",
    "payment_instructions_cashier": "Silakan bayar di loket kasir.",
    "card": "Kami akan memberikan kartu pasien. Silakan tunjukkan pada kunjungan berikutnya.",
    "system_information_detail": "Informasi sistem secara rinci",
    "system_information_detail_link": "Lihat informasi sistem secara rinci",
    "notify_pregnancy_office": "Silakan konfirmasi prosedur pelaporan kehamilan di pemerintah daerah tempat tinggal Anda.",
    "mother_child_handbook": "Silakan ambil Buku Kesehatan Ibu dan Anak.",
    "checkup_tickets": "Silakan periksa cara menggunakan tiket pemeriksaan kehamilan dan kupon subsidi.",
    "hospital_reservation": "Tentukan rumah sakit atau klinik persalinan sejak awal dan buat reservasi.",
    "insurance_payment": "Silakan periksa asuransi kesehatan dan cara pembayaran biaya persalinan.",
    "financial_support": "Silakan periksa dukungan biaya seperti tunjangan sekaligus persalinan dan pengasuhan anak.",
    "municipal_support": "Anda dapat menggunakan layanan konsultasi dan sistem dukungan pemerintah daerah.",
    "interpreter_support": "Silakan berkonsultasi jika membutuhkan penerjemah atau konsultasi multibahasa.",
    "emergency_contact_info": "Pastikan Anda mengetahui kontak untuk malam hari dan hari libur.",
    "bring_documents": "Silakan periksa dokumen dan barang yang perlu dibawa saat berkunjung."
  },
  "russian": {
    "language_instruction": "Пожалуйста, выберите язык, который вы понимаете.",
    "reception": "Регистратура",
    "reception1": "Регистратура",
    "waiting_room": "Зал ожидания",
    "consultation_room": "Кабинет осмотра",
    "first_time": "Вы пришли впервые?",
    "yes": "Да",
    "no": "Нет",
    "yes1": "Да",
    "no1": "Нет",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Пожалуйста, выберите причину сегодняшнего визита.",
    "absence_period": "Менструация прекратилась",
    "nausea": "Тошнота",
    "possible_pregnancy": "Возможна беременность",
    "inconsistent_period": "Нерегулярные месячные",
    "period_pain": "Болит живот во время месячных",
    "itching": "Зуд в области наружных половых органов",
    "stomach_pain": "Боль в животе",
    "infertility_question": "Хочу спросить о бесплодии",
    "other": "Другое",
    "question": "Медицинская анкета",
    "fill_form_waiting_room": "Пожалуйста, заполните медицинскую анкету в зале ожидания.",
    "finished_filling_form": "Когда закончите, принесите её нам.",
    "take_weight": "До осмотра измерьте вес и давление и сдайте мочу.",
    "weit_here": "Пожалуйста, ждите в указанном месте до осмотра.",
    "staff_notification": "Сотрудник подскажет, куда идти.",
    "call_order": "Мы будем вызывать по имени или номеру по порядку.",
    "call_order2": "Порядок может измениться в зависимости от ситуации.",
    "medicines": "Лекарства",
    "give_medicines_in_hospital": "Лекарства выдадут в больнице после осмотра.",
    "give_medicines_out_of_hospital": "Возможно, лекарства нужно будет купить в аптеке вне больницы.",
    "prescription_validity": "Рецепт действителен 4 дня, включая дату выдачи.",
    "payment_instructions_machine": "Пожалуйста, оплатите в автомате оплаты.",
    "payment_instructions_cashier": "Пожалуйста, оплатите в кассе.",
    "card": "Мы выдадим вам карту пациента. Показывайте её со следующего визита.",
    "system_information_detail": "Подробная информация о системах поддержки",
    "system_information_detail_link": "Посмотреть подробную информацию о системах",
    "notify_pregnancy_office": "Пожалуйста, уточните порядок уведомления о беременности в муниципалитете по месту жительства.",
    "mother_child_handbook": "Пожалуйста, получите книжку здоровья матери и ребенка.",
    "checkup_tickets": "Проверьте, как пользоваться талонами на осмотр беременных и субсидийными купонами.",
    "hospital_reservation": "Заранее выберите больницу или клинику для родов и сделайте запись.",
    "insurance_payment": "Проверьте медицинскую страховку и способ оплаты расходов на роды.",
    "financial_support": "Проверьте финансовую поддержку, например единовременное пособие на роды и уход за ребенком.",
    "municipal_support": "Вы можете пользоваться консультациями и программами поддержки муниципалитета.",
    "interpreter_support": "Обратитесь к нам, если нужен переводчик или консультация на разных языках.",
    "emergency_contact_info": "Заранее проверьте контакты для ночного времени и праздничных дней.",
    "bring_documents": "Проверьте документы и вещи, которые нужно взять на прием."
  },
  "nepali": {
    "language_instruction": "कृपया तपाईंले बुझ्ने भाषा छान्नुहोस्।",
    "reception": "रिसेप्सन",
    "reception1": "रिसेप्सन",
    "waiting_room": "प्रतीक्षा कोठा",
    "consultation_room": "जाँच कोठा",
    "first_time": "के यो तपाईंको पहिलो भेट हो?",
    "yes": "हो",
    "no": "होइन",
    "yes1": "हो",
    "no1": "होइन",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "आज आउनुको कारण छान्नुहोस्।",
    "absence_period": "महिनावारी रोकिएको छ",
    "nausea": "वाकवाकी",
    "possible_pregnancy": "गर्भवती हुन सक्छु",
    "inconsistent_period": "महिनावारी नियमित छैन",
    "period_pain": "महिनावारी हुँदा पेट दुख्छ",
    "itching": "बाहिरी यौनाङ्ग वरिपरि चिलाउँछ",
    "stomach_pain": "पेट दुख्छ",
    "infertility_question": "बाँझोपनबारे सोध्न चाहन्छु",
    "other": "अन्य",
    "question": "चिकित्सा प्रश्नावली",
    "fill_form_waiting_room": "कृपया प्रतीक्षा कोठामा चिकित्सा प्रश्नावली भर्नुहोस्।",
    "finished_filling_form": "भरेपछि कृपया हामीकहाँ ल्याउनुहोस्।",
    "take_weight": "जाँचअघि तौल, रक्तचाप र पिसाब जाँच गर्नुहोस्।",
    "weit_here": "जाँचसम्म तोकिएको ठाउँमा पर्खनुहोस्।",
    "staff_notification": "कहाँ जाने भनेर कर्मचारीले बताउनेछन्।",
    "call_order": "नाम वा नम्बरको क्रम अनुसार बोलाइनेछ।",
    "call_order2": "स्थिति अनुसार क्रम परिवर्तन हुन सक्छ।",
    "medicines": "औषधि",
    "give_medicines_in_hospital": "जाँचपछि औषधि अस्पतालभित्र दिइनेछ।",
    "give_medicines_out_of_hospital": "कहिलेकाहीँ अस्पताल बाहिरको फार्मेसीमा औषधि किन्नुपर्ने हुन सक्छ।",
    "prescription_validity": "प्रिस्क्रिप्सन जारी भएको दिनसहित ४ दिन मान्य हुन्छ।",
    "payment_instructions_machine": "कृपया स्वचालित भुक्तानी मेसिनमा भुक्तानी गर्नुहोस्।",
    "payment_instructions_cashier": "कृपया क्यासियर काउन्टरमा भुक्तानी गर्नुहोस्।",
    "card": "हामी तपाईंलाई बिरामी कार्ड दिनेछौँ। अर्को पटकदेखि देखाउनुहोस्।",
    "system_information_detail": "प्रणाली जानकारीको विवरण",
    "system_information_detail_link": "प्रणाली जानकारीको विवरण हेर्नुहोस्",
    "notify_pregnancy_office": "बसोबास गर्ने नगरपालिकामा गर्भावस्था सूचना प्रक्रिया पुष्टि गर्नुहोस्।",
    "mother_child_handbook": "आमा र बच्चा स्वास्थ्य पुस्तिका लिनुहोस्।",
    "checkup_tickets": "गर्भवती जाँच टिकट र सहायता कुपन कसरी प्रयोग गर्ने पुष्टि गर्नुहोस्।",
    "hospital_reservation": "प्रसूति गर्ने अस्पताल वा क्लिनिक चाँडै छानेर आरक्षण गर्नुहोस्।",
    "insurance_payment": "स्वास्थ्य बीमा र प्रसूति खर्च भुक्तानी तरिका पुष्टि गर्नुहोस्।",
    "financial_support": "प्रसूति तथा बालपालन एकमुष्ट भत्ता जस्ता आर्थिक सहायता प्रणाली पुष्टि गर्नुहोस्।",
    "municipal_support": "नगरपालिकाको परामर्श सेवा र सहायता कार्यक्रम प्रयोग गर्न सक्नुहुन्छ।",
    "interpreter_support": "दोभाषे वा बहुभाषी परामर्श चाहिन्छ भने सोध्नुहोस्।",
    "emergency_contact_info": "राति र बिदाका दिनको सम्पर्क नम्बर पुष्टि गर्नुहोस्।",
    "bring_documents": "भेटका लागि चाहिने कागजात र सामान पुष्टि गर्नुहोस्।"
  },
  "laotian": {
    "language_instruction": "ກະລຸນາເລືອກພາສາທີ່ທ່ານເຂົ້າໃຈ.",
    "reception": "ຕ້ອນຮັບ",
    "reception1": "ຕ້ອນຮັບ",
    "waiting_room": "ຫ້ອງລໍຖ້າ",
    "consultation_room": "ຫ້ອງກວດ",
    "first_time": "ນີ້ແມ່ນການມາຄັ້ງທຳອິດບໍ?",
    "yes": "ແມ່ນ",
    "no": "ບໍ່",
    "yes1": "ແມ່ນ",
    "no1": "ບໍ່",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "ກະລຸນາເລືອກເຫດຜົນທີ່ມາມື້ນີ້.",
    "absence_period": "ປະຈຳເດືອນຢຸດ",
    "nausea": "ປວດຮາກ",
    "possible_pregnancy": "ອາດຈະຖືພາ",
    "inconsistent_period": "ປະຈຳເດືອນບໍ່ສະໝ່ຳສະເໝີ",
    "period_pain": "ປວດທ້ອງເວລາມີປະຈຳເດືອນ",
    "itching": "ຄັນບໍລິເວນອະວັຍະວະເພດພາຍນອກ",
    "stomach_pain": "ປວດທ້ອງ",
    "infertility_question": "ຢາກຖາມເລື່ອງມີລູກຍາກ",
    "other": "ອື່ນໆ",
    "question": "ແບບສອບຖາມທາງການແພດ",
    "fill_form_waiting_room": "ກະລຸນາຕື່ມແບບສອບຖາມທາງການແພດໃນຫ້ອງລໍຖ້າ.",
    "finished_filling_form": "ເມື່ອຕື່ມແລ້ວ ກະລຸນານຳມາໃຫ້ພວກເຮົາ.",
    "take_weight": "ກ່ອນກວດ ກະລຸນາຊັ່ງນ້ຳໜັກ ວັດຄວາມດັນ ແລະ ກວດປັດສະວະ.",
    "weit_here": "ກະລຸນາລໍຖ້າຢູ່ບ່ອນທີ່ກຳນົດຈົນຮອດເວລາກວດ.",
    "staff_notification": "ພະນັກງານຈະແນະນຳວ່າຕ້ອງໄປໃສ.",
    "call_order": "ຈະເອີ້ນຕາມລຳດັບຊື່ ຫຼື ໝາຍເລກ.",
    "call_order2": "ລຳດັບອາດປ່ຽນໄດ້ຕາມສະຖານະການ.",
    "medicines": "ຢາ",
    "give_medicines_in_hospital": "ຢາຈະຖືກມອບໃຫ້ໃນໂຮງໝໍຫຼັງກວດ.",
    "give_medicines_out_of_hospital": "ບາງກໍລະນີຕ້ອງຊື້ຢາທີ່ຮ້ານຂາຍຢານອກໂຮງໝໍ.",
    "prescription_validity": "ໃບສັ່ງຢາໃຊ້ໄດ້ 4 ມື້ ລວມມື້ອອກໃບ.",
    "payment_instructions_machine": "ກະລຸນາຈ່າຍເງິນທີ່ເຄື່ອງຈ່າຍເງິນອັດຕະໂນມັດ.",
    "payment_instructions_cashier": "ກະລຸນາຈ່າຍເງິນທີ່ເຄົາເຕີການເງິນ.",
    "card": "ພວກເຮົາຈະໃຫ້ບັດກວດ. ຄັ້ງໜ້າກະລຸນາສະແດງບັດນີ້.",
    "system_information_detail": "ລາຍລະອຽດຂໍ້ມູນລະບົບ",
    "system_information_detail_link": "ເບິ່ງລາຍລະອຽດຂໍ້ມູນລະບົບ",
    "notify_pregnancy_office": "ກະລຸນາຢືນຢັນຂັ້ນຕອນແຈ້ງຖືພາກັບເທດສະບານທີ່ທ່ານອາໄສ.",
    "mother_child_handbook": "ກະລຸນາຮັບປື້ມສຸຂະພາບແມ່ແລະເດັກ.",
    "checkup_tickets": "ກະລຸນາຢືນຢັນວິທີໃຊ້ບັດກວດຄັນແລະຄູປອງຊ່ວຍເຫຼືອ.",
    "hospital_reservation": "ກະລຸນາເລືອກໂຮງໝໍ ຫຼື ຄລິນິກສຳລັບຄອດແຕ່ເນີ່ນ ແລະ ຈອງ.",
    "insurance_payment": "ກະລຸນາຢືນຢັນປະກັນສຸຂະພາບ ແລະ ວິທີຈ່າຍຄ່າຄອດ.",
    "financial_support": "ກະລຸນາຢືນຢັນລະບົບຊ່ວຍເຫຼືອຄ່າໃຊ້ຈ່າຍເຊັ່ນເງິນຊ່ວຍຄອດ.",
    "municipal_support": "ສາມາດໃຊ້ບ່ອນປຶກສາ ແລະ ລະບົບຊ່ວຍເຫຼືອຂອງເທດສະບານ.",
    "interpreter_support": "ຖ້າຕ້ອງການລ່າມ ຫຼື ການປຶກສາຫຼາຍພາສາ ກະລຸນາບອກ.",
    "emergency_contact_info": "ກະລຸນາຢືນຢັນເບີຕິດຕໍ່ກາງຄືນ ແລະ ວັນພັກ.",
    "bring_documents": "ກະລຸນາຢືນຢັນເອກະສານ ແລະ ຂອງທີ່ຕ້ອງນຳມາເມື່ອມາກວດ."
  },
  "ukrainian": {
    "language_instruction": "Будь ласка, виберіть мову, яку ви розумієте.",
    "reception": "Реєстратура",
    "reception1": "Реєстратура",
    "waiting_room": "Зал ожидания",
    "consultation_room": "Кабинет осмотра",
    "first_time": "Це ваш перший візит?",
    "yes": "Так",
    "no": "Ні",
    "yes1": "Так",
    "no1": "Ні",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Пожалуйста, выберите причину сегодняшнего визита.",
    "absence_period": "Менструация прекратилась",
    "nausea": "Тошнота",
    "possible_pregnancy": "Возможна беременность",
    "inconsistent_period": "Нерегулярные месячные",
    "period_pain": "Болит живот во время месячных",
    "itching": "Зуд в области наружных половых органов",
    "stomach_pain": "Боль в животе",
    "infertility_question": "Хочу спросить о бесплодии",
    "other": "Другое",
    "question": "Медична анкета",
    "fill_form_waiting_room": "Пожалуйста, заполните медицинскую анкету в зале ожидания.",
    "finished_filling_form": "Когда закончите, принесите её нам.",
    "take_weight": "До осмотра измерьте вес и давление и сдайте мочу.",
    "weit_here": "Пожалуйста, ждите в указанном месте до осмотра.",
    "staff_notification": "Сотрудник подскажет, куда идти.",
    "call_order": "Мы будем вызывать по имени или номеру по порядку.",
    "call_order2": "Порядок может измениться в зависимости от ситуации.",
    "medicines": "Лекарства",
    "give_medicines_in_hospital": "Лекарства выдадут в больнице после осмотра.",
    "give_medicines_out_of_hospital": "Возможно, лекарства нужно будет купить в аптеке вне больницы.",
    "prescription_validity": "Рецепт действителен 4 дня, включая дату выдачи.",
    "payment_instructions_machine": "Пожалуйста, оплатите в автомате оплаты.",
    "payment_instructions_cashier": "Пожалуйста, оплатите в кассе.",
    "card": "Мы выдадим вам карту пациента. Показывайте её со следующего визита.",
    "system_information_detail": "Подробная информация о системах поддержки",
    "system_information_detail_link": "Посмотреть подробную информацию о системах",
    "notify_pregnancy_office": "Пожалуйста, уточните порядок уведомления о беременности в муниципалитете по месту жительства.",
    "mother_child_handbook": "Пожалуйста, получите книжку здоровья матери и ребенка.",
    "checkup_tickets": "Проверьте, как пользоваться талонами на осмотр беременных и субсидийными купонами.",
    "hospital_reservation": "Заранее выберите больницу или клинику для родов и сделайте запись.",
    "insurance_payment": "Проверьте медицинскую страховку и способ оплаты расходов на роды.",
    "financial_support": "Проверьте финансовую поддержку, например единовременное пособие на роды и уход за ребенком.",
    "municipal_support": "Вы можете пользоваться консультациями и программами поддержки муниципалитета.",
    "interpreter_support": "Обратитесь к нам, если нужен переводчик или консультация на разных языках.",
    "emergency_contact_info": "Заранее проверьте контакты для ночного времени и праздничных дней.",
    "bring_documents": "Проверьте документы и вещи, которые нужно взять на прием."
  },
  "dari": {
    "language_instruction": "لطفاً زبانی را که می‌فهمید انتخاب کنید.",
    "reception": "پذیرش",
    "reception1": "پذیرش",
    "waiting_room": "اتاق انتظار",
    "consultation_room": "اتاق معاینه",
    "first_time": "آیا این اولین مراجعه شما است؟",
    "yes": "بلی",
    "no": "نخیر",
    "yes1": "بلی",
    "no1": "نخیر",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "لطفاً دلیل مراجعه امروز را انتخاب کنید.",
    "absence_period": "عادت ماهانه قطع شده است",
    "nausea": "حالت تهوع",
    "possible_pregnancy": "ممکن است باردار باشم",
    "inconsistent_period": "عادت ماهانه منظم نیست",
    "period_pain": "هنگام عادت ماهانه درد شکم دارم",
    "itching": "خارش در ناحیه بیرونی تناسلی",
    "stomach_pain": "درد شکم",
    "infertility_question": "می‌خواهم درباره ناباروری بپرسم",
    "other": "دیگر",
    "question": "فورم صحی",
    "fill_form_waiting_room": "لطفاً فورم صحی را در اتاق انتظار پر کنید.",
    "finished_filling_form": "پس از تکمیل، لطفاً آن را بیاورید.",
    "take_weight": "پیش از معاینه، وزن و فشار خون را اندازه بگیرید و آزمایش ادرار بدهید.",
    "weit_here": "لطفاً تا زمان معاینه در محل تعیین‌شده منتظر بمانید.",
    "staff_notification": "کارمند راهنمایی می‌کند کجا بروید.",
    "call_order": "به ترتیب نام یا شماره صدا زده می‌شوید.",
    "call_order2": "ترتیب ممکن است بسته به وضعیت تغییر کند.",
    "medicines": "دوا",
    "give_medicines_in_hospital": "دوا پس از معاینه در داخل شفاخانه داده می‌شود.",
    "give_medicines_out_of_hospital": "ممکن است لازم باشد دوا را از دواخانه بیرون شفاخانه بخرید.",
    "prescription_validity": "نسخه از روز صدور به شمول همان روز ۴ روز اعتبار دارد.",
    "payment_instructions_machine": "لطفاً در دستگاه پرداخت خودکار پرداخت کنید.",
    "payment_instructions_cashier": "لطفاً در صندوق پرداخت کنید.",
    "card": "کارت معاینه به شما داده می‌شود. از مراجعه بعدی آن را نشان دهید.",
    "system_information_detail": "جزئیات معلومات سیستم",
    "system_information_detail_link": "دیدن جزئیات معلومات سیستم",
    "notify_pregnancy_office": "لطفاً مراحل اطلاع‌دهی بارداری را در شاروالی محل زندگی خود تأیید کنید.",
    "mother_child_handbook": "لطفاً دفترچه سلامت مادر و کودک را دریافت کنید.",
    "checkup_tickets": "لطفاً طریقه استفاده از برگه‌های معاینه بارداری و کوپن‌های کمک را تأیید کنید.",
    "hospital_reservation": "شفاخانه یا کلینیک زایمان را زود انتخاب و رزرو کنید.",
    "insurance_payment": "بیمه صحی و روش پرداخت هزینه زایمان را تأیید کنید.",
    "financial_support": "کمک‌های مالی مانند کمک‌هزینه زایمان را تأیید کنید.",
    "municipal_support": "می‌توانید از خدمات مشاوره و حمایت شاروالی استفاده کنید.",
    "interpreter_support": "اگر به ترجمان یا مشاوره چندزبانه نیاز دارید، بگویید.",
    "emergency_contact_info": "شماره تماس شب و روزهای رخصتی را تأیید کنید.",
    "bring_documents": "اسناد و وسایل لازم برای مراجعه را تأیید کنید."
  },
  "sinhala": {
    "language_instruction": "කරුණාකර ඔබට තේරෙන භාෂාව තෝරන්න.",
    "reception": "පිළිගැනීම",
    "reception1": "පිළිගැනීම",
    "waiting_room": "Waiting room",
    "consultation_room": "Consultation room",
    "first_time": "මෙය ඔබගේ පළමු පැමිණීමද?",
    "yes": "ඔව්",
    "no": "නැහැ",
    "yes1": "ඔව්",
    "no1": "නැහැ",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "අද පැමිණි හේතුව තෝරන්න.",
    "absence_period": "මාසිකය නතර වී ඇත",
    "nausea": "වමනය වගේ දැනීම",
    "possible_pregnancy": "ගර්භණී විය හැක",
    "inconsistent_period": "මාසිකය අක්‍රමවත්ය",
    "period_pain": "මාසිකයේදී බඩ රිදේ",
    "itching": "බාහිර ලිංගික ප්‍රදේශයේ කැසීම",
    "stomach_pain": "බඩ රිදීම",
    "infertility_question": "වඳභාවය ගැන අසන්න කැමතියි",
    "other": "වෙනත්",
    "question": "වෛද්‍ය ප්‍රශ්න පත්‍රය",
    "fill_form_waiting_room": "කරුණාකර රැඳී සිටින කාමරයේ වෛද්‍ය ප්‍රශ්න පත්‍රය පුරවන්න.",
    "finished_filling_form": "පුරවා අවසන් වූ පසු කරුණාකර ගෙන එන්න.",
    "take_weight": "පරීක්ෂණයට පෙර බර, රුධිර පීඩනය සහ මුත්‍රා පරීක්ෂාව කරන්න.",
    "weit_here": "පරීක්ෂණය තෙක් නියමිත ස්ථානයේ රැඳී සිටින්න.",
    "staff_notification": "කාර්ය මණ්ඩලය යා යුතු තැන කියා දෙනු ඇත.",
    "call_order": "නම හෝ අංකය අනුව අමතනු ලැබේ.",
    "call_order2": "තත්ත්වය අනුව පිළිවෙළ වෙනස් විය හැක.",
    "medicines": "ඖෂධ",
    "give_medicines_in_hospital": "පරීක්ෂණයෙන් පසු රෝහල තුළ ඖෂධ ලබා දෙනු ඇත.",
    "give_medicines_out_of_hospital": "රෝහලෙන් පිටත ඖෂධ ශාලාවකින් මිලදී ගත යුතු විය හැක.",
    "prescription_validity": "වට්ටෝරුව නිකුත් කළ දිනය ඇතුළුව දින 4ක් වලංගුය.",
    "payment_instructions_machine": "ස්වයංක්‍රීය ගෙවීම් යන්ත්‍රයෙන් ගෙවන්න.",
    "payment_instructions_cashier": "ගෙවීම් කවුන්ටරයෙන් ගෙවන්න.",
    "card": "රෝගී කාඩ්පත ලබා දෙන්නෙමු. ඊළඟ වතාවේ සිට පෙන්වන්න.",
    "system_information_detail": "පද්ධති තොරතුරු විස්තර",
    "system_information_detail_link": "පද්ධති තොරතුරු විස්තර බලන්න",
    "notify_pregnancy_office": "ඔබ ජීවත් වන පළාත් පාලන ආයතනයේ ගර්භණී බව දැනුම්දීමේ ක්‍රමය තහවුරු කරන්න.",
    "mother_child_handbook": "මව් හා ළමා සෞඛ්‍ය අත්පොත ලබා ගන්න.",
    "checkup_tickets": "ගර්භණී පරීක්ෂණ පත්‍ර සහ සහනාධාර කූපන් භාවිතා කරන ආකාරය තහවුරු කරන්න.",
    "hospital_reservation": "ප්‍රසූතිය සිදු කරන රෝහල හෝ ක්ලිනික් එක ඉක්මනින් තීරණය කර වෙන්කරවා ගන්න.",
    "insurance_payment": "සෞඛ්‍ය රක්ෂණය සහ ප්‍රසූති වියදම් ගෙවීමේ ක්‍රමය තහවුරු කරන්න.",
    "financial_support": "ප්‍රසූති හා දරුවා රැකබලා ගැනීමේ එකවර දීමනා වැනි මූල්‍ය සහාය පද්ධති තහවුරු කරන්න.",
    "municipal_support": "පළාත් පාලන ආයතනයේ උපදේශන කවුළුව සහ සහාය පද්ධති භාවිතා කළ හැක.",
    "interpreter_support": "භාෂා පරිවර්තකයෙකු හෝ බහුභාෂා උපදේශනයක් අවශ්‍ය නම් කරුණාකර කියන්න.",
    "emergency_contact_info": "රාත්‍රී සහ නිවාඩු දින සම්බන්ධතා අංකය තහවුරු කර ගන්න.",
    "bring_documents": "පරීක්ෂණයට එන විට අවශ්‍ය ලේඛන සහ ගෙන ආ යුතු දේවල් තහවුරු කරන්න."
  },
  "malay": {
    "language_instruction": "Sila pilih bahasa yang anda fahami.",
    "reception": "Penerimaan",
    "reception1": "Penerimaan",
    "waiting_room": "Ruang tunggu",
    "consultation_room": "Ruang konsultasi",
    "first_time": "Apakah ini kunjungan pertama Anda?",
    "yes": "Ya",
    "no": "Tidak",
    "yes1": "Ya",
    "no1": "Tidak",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "Silakan pilih alasan kunjungan Anda hari ini.",
    "absence_period": "Menstruasi berhenti",
    "nausea": "Mual",
    "possible_pregnancy": "Mungkin hamil",
    "inconsistent_period": "Menstruasi tidak teratur",
    "period_pain": "Sakit perut saat menstruasi",
    "itching": "Gatal pada vulva",
    "stomach_pain": "Sakit perut",
    "infertility_question": "Ingin bertanya tentang infertilitas",
    "other": "Lainnya",
    "question": "Kuesioner medis",
    "fill_form_waiting_room": "Silakan isi kuesioner medis di ruang tunggu.",
    "finished_filling_form": "Setelah selesai mengisi, silakan bawa kepada kami.",
    "take_weight": "Sebelum pemeriksaan, ukur berat badan dan tekanan darah, serta lakukan tes urine.",
    "weit_here": "Silakan tunggu di tempat yang ditentukan sampai pemeriksaan.",
    "staff_notification": "Staf akan memberi tahu ke mana Anda harus pergi.",
    "call_order": "Kami akan memanggil sesuai urutan nama atau nomor.",
    "call_order2": "Urutan dapat berubah tergantung situasi.",
    "medicines": "Obat",
    "give_medicines_in_hospital": "Obat akan diberikan di dalam rumah sakit setelah pemeriksaan.",
    "give_medicines_out_of_hospital": "Anda mungkin perlu membeli obat di apotek luar rumah sakit.",
    "prescription_validity": "Resep berlaku 4 hari termasuk tanggal penerbitan.",
    "payment_instructions_machine": "Silakan bayar di mesin pembayaran otomatis.",
    "payment_instructions_cashier": "Silakan bayar di loket kasir.",
    "card": "Kami akan memberikan kartu pasien. Silakan tunjukkan pada kunjungan berikutnya.",
    "system_information_detail": "Informasi sistem secara rinci",
    "system_information_detail_link": "Lihat informasi sistem secara rinci",
    "notify_pregnancy_office": "Silakan konfirmasi prosedur pelaporan kehamilan di pemerintah daerah tempat tinggal Anda.",
    "mother_child_handbook": "Silakan ambil Buku Kesehatan Ibu dan Anak.",
    "checkup_tickets": "Silakan periksa cara menggunakan tiket pemeriksaan kehamilan dan kupon subsidi.",
    "hospital_reservation": "Tentukan rumah sakit atau klinik persalinan sejak awal dan buat reservasi.",
    "insurance_payment": "Silakan periksa asuransi kesehatan dan cara pembayaran biaya persalinan.",
    "financial_support": "Silakan periksa dukungan biaya seperti tunjangan sekaligus persalinan dan pengasuhan anak.",
    "municipal_support": "Anda dapat menggunakan layanan konsultasi dan sistem dukungan pemerintah daerah.",
    "interpreter_support": "Silakan berkonsultasi jika membutuhkan penerjemah atau konsultasi multibahasa.",
    "emergency_contact_info": "Pastikan Anda mengetahui kontak untuk malam hari dan hari libur.",
    "bring_documents": "Silakan periksa dokumen dan barang yang perlu dibawa saat berkunjung."
  },
  "myanmar": {
    "language_instruction": "သင်နားလည်သော ဘာသာစကားကို ရွေးပါ။",
    "reception": "လက်ခံရေး",
    "reception1": "လက်ခံရေး",
    "waiting_room": "Waiting room",
    "consultation_room": "Consultation room",
    "first_time": "ပထမဆုံး လာရောက်ခြင်းလား?",
    "yes": "ဟုတ်ကဲ့",
    "no": "မဟုတ်ပါ",
    "yes1": "ဟုတ်ကဲ့",
    "no1": "မဟုတ်ပါ",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "ယနေ့လာရောက်ရသည့် အကြောင်းရင်းကို ရွေးပါ။",
    "absence_period": "ရာသီရပ်သွားသည်",
    "nausea": "အန်ချင်သည်",
    "possible_pregnancy": "ကိုယ်ဝန်ရှိနိုင်သည်",
    "inconsistent_period": "ရာသီမမှန်ပါ",
    "period_pain": "ရာသီလာချိန် ဗိုက်နာသည်",
    "itching": "ပြင်ပလိင်အင်္ဂါယားယံသည်",
    "stomach_pain": "ဗိုက်နာသည်",
    "infertility_question": "မွေးဖွားနိုင်မှုမရှိခြင်းအကြောင်း မေးချင်သည်",
    "other": "အခြား",
    "question": "ဆေးဘက်ဆိုင်ရာ မေးခွန်းလွှာ",
    "fill_form_waiting_room": "စောင့်ဆိုင်းခန်းတွင် ဆေးဘက်ဆိုင်ရာ မေးခွန်းလွှာကို ဖြည့်ပါ။",
    "finished_filling_form": "ဖြည့်ပြီးပါက ယူလာပါ။",
    "take_weight": "စစ်ဆေးမှုမပြုမီ ကိုယ်အလေးချိန်၊ သွေးပေါင်ချိန်နှင့် ဆီးစစ်ပါ။",
    "weit_here": "စစ်ဆေးချိန်အထိ သတ်မှတ်နေရာတွင် စောင့်ပါ။",
    "staff_notification": "ဘယ်ကိုသွားရမည်ကို ဝန်ထမ်းက ပြောပြပါမည်။",
    "call_order": "အမည် သို့မဟုတ် နံပါတ် အစဉ်လိုက် ခေါ်ပါမည်။",
    "call_order2": "အခြေအနေအပေါ်မူတည်၍ အစဉ်ပြောင်းနိုင်သည်။",
    "medicines": "ဆေး",
    "give_medicines_in_hospital": "စစ်ဆေးပြီးနောက် ဆေးကို ဆေးရုံအတွင်း ပေးပါမည်။",
    "give_medicines_out_of_hospital": "ဆေးရုံပြင်ပ ဆေးဆိုင်တွင် ဝယ်ယူရနိုင်သည်။",
    "prescription_validity": "ဆေးညွှန်းသည် ထုတ်သည့်နေ့အပါအဝင် ၄ ရက် သက်တမ်းရှိသည်။",
    "payment_instructions_machine": "အလိုအလျောက် ငွေပေးချေစက်တွင် ငွေပေးချေပါ။",
    "payment_instructions_cashier": "ငွေရှင်းကောင်တာတွင် ငွေပေးချေပါ။",
    "card": "လူနာကတ်ပေးပါမည်။ နောက်တစ်ကြိမ်မှစ၍ ပြပါ။",
    "system_information_detail": "စနစ်အချက်အလက် အသေးစိတ်",
    "system_information_detail_link": "စနစ်အချက်အလက် အသေးစိတ်ကြည့်ရန်",
    "notify_pregnancy_office": "သင်နေထိုင်သော မြို့နယ်ရုံးတွင် ကိုယ်ဝန်ရှိကြောင်း အကြောင်းကြားရမည့် လုပ်ထုံးလုပ်နည်းကို အတည်ပြုပါ။",
    "mother_child_handbook": "မိခင်နှင့်ကလေး ကျန်းမာရေးစာအုပ်ကို ယူပါ။",
    "checkup_tickets": "ကိုယ်ဝန်ဆောင် စစ်ဆေးရေးလက်မှတ်နှင့် အထောက်အပံ့ကူပွန် အသုံးပြုပုံကို အတည်ပြုပါ။",
    "hospital_reservation": "မွေးဖွားမည့် ဆေးရုံ သို့မဟုတ် ကလင်နစ်ကို စောစောဆုံးဖြတ်ပြီး ကြိုတင်စာရင်းသွင်းပါ။",
    "insurance_payment": "ကျန်းမာရေးအာမခံနှင့် မွေးဖွားစရိတ်ပေးချေမှုနည်းလမ်းကို အတည်ပြုပါ။",
    "financial_support": "မွေးဖွားမှုနှင့် ကလေးစောင့်ရှောက်မှု တစ်ကြိမ်တည်း ထောက်ပံ့ကြေးကဲ့သို့ ငွေကြေးအထောက်အပံ့များကို အတည်ပြုပါ။",
    "municipal_support": "မြို့နယ်၏ ဆွေးနွေးတိုင်ပင်ရေးနှင့် အထောက်အပံ့စနစ်များကို အသုံးပြုနိုင်သည်။",
    "interpreter_support": "ဘာသာပြန်သူ သို့မဟုတ် ဘာသာစကားများစွာဖြင့် ဆွေးနွေးရန် လိုအပ်ပါက ပြောပါ။",
    "emergency_contact_info": "ညအချိန်နှင့် အားလပ်ရက်များအတွက် ဆက်သွယ်ရန် နံပါတ်ကို အတည်ပြုထားပါ။",
    "bring_documents": "လာရောက်စစ်ဆေးရာတွင် လိုအပ်သော စာရွက်စာတမ်းများနှင့် ယူလာရမည့်ပစ္စည်းများကို အတည်ပြုပါ။"
  },
  "bengali": {
    "language_instruction": "আপনি যে ভাষা বুঝতে পারেন তা নির্বাচন করুন।",
    "reception": "রিসেপশন",
    "reception1": "রিসেপশন",
    "waiting_room": "प्रतीक्षा कोठा",
    "consultation_room": "जाँच कोठा",
    "first_time": "এটি কি আপনার প্রথমবার?",
    "yes": "হ্যাঁ",
    "no": "না",
    "yes1": "হ্যাঁ",
    "no1": "না",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "आज आउनुको कारण छान्नुहोस्।",
    "absence_period": "महिनावारी रोकिएको छ",
    "nausea": "वाकवाकी",
    "possible_pregnancy": "गर्भवती हुन सक्छु",
    "inconsistent_period": "महिनावारी नियमित छैन",
    "period_pain": "महिनावारी हुँदा पेट दुख्छ",
    "itching": "बाहिरी यौनाङ्ग वरिपरि चिलाउँछ",
    "stomach_pain": "पेट दुख्छ",
    "infertility_question": "बाँझोपनबारे सोध्न चाहन्छु",
    "other": "अन्य",
    "question": "চিকিৎসা প্রশ্নপত্র",
    "fill_form_waiting_room": "कृपया प्रतीक्षा कोठामा चिकित्सा प्रश्नावली भर्नुहोस्।",
    "finished_filling_form": "भरेपछि कृपया हामीकहाँ ल्याउनुहोस्।",
    "take_weight": "जाँचअघि तौल, रक्तचाप र पिसाब जाँच गर्नुहोस्।",
    "weit_here": "जाँचसम्म तोकिएको ठाउँमा पर्खनुहोस्।",
    "staff_notification": "कहाँ जाने भनेर कर्मचारीले बताउनेछन्।",
    "call_order": "नाम वा नम्बरको क्रम अनुसार बोलाइनेछ।",
    "call_order2": "स्थिति अनुसार क्रम परिवर्तन हुन सक्छ।",
    "medicines": "औषधि",
    "give_medicines_in_hospital": "जाँचपछि औषधि अस्पतालभित्र दिइनेछ।",
    "give_medicines_out_of_hospital": "कहिलेकाहीँ अस्पताल बाहिरको फार्मेसीमा औषधि किन्नुपर्ने हुन सक्छ।",
    "prescription_validity": "प्रिस्क्रिप्सन जारी भएको दिनसहित ४ दिन मान्य हुन्छ।",
    "payment_instructions_machine": "कृपया स्वचालित भुक्तानी मेसिनमा भुक्तानी गर्नुहोस्।",
    "payment_instructions_cashier": "कृपया क्यासियर काउन्टरमा भुक्तानी गर्नुहोस्।",
    "card": "हामी तपाईंलाई बिरामी कार्ड दिनेछौँ। अर्को पटकदेखि देखाउनुहोस्।",
    "system_information_detail": "प्रणाली जानकारीको विवरण",
    "system_information_detail_link": "प्रणाली जानकारीको विवरण हेर्नुहोस्",
    "notify_pregnancy_office": "बसोबास गर्ने नगरपालिकामा गर्भावस्था सूचना प्रक्रिया पुष्टि गर्नुहोस्।",
    "mother_child_handbook": "आमा र बच्चा स्वास्थ्य पुस्तिका लिनुहोस्।",
    "checkup_tickets": "गर्भवती जाँच टिकट र सहायता कुपन कसरी प्रयोग गर्ने पुष्टि गर्नुहोस्।",
    "hospital_reservation": "प्रसूति गर्ने अस्पताल वा क्लिनिक चाँडै छानेर आरक्षण गर्नुहोस्।",
    "insurance_payment": "स्वास्थ्य बीमा र प्रसूति खर्च भुक्तानी तरिका पुष्टि गर्नुहोस्।",
    "financial_support": "प्रसूति तथा बालपालन एकमुष्ट भत्ता जस्ता आर्थिक सहायता प्रणाली पुष्टि गर्नुहोस्।",
    "municipal_support": "नगरपालिकाको परामर्श सेवा र सहायता कार्यक्रम प्रयोग गर्न सक्नुहुन्छ।",
    "interpreter_support": "दोभाषे वा बहुभाषी परामर्श चाहिन्छ भने सोध्नुहोस्।",
    "emergency_contact_info": "राति र बिदाका दिनको सम्पर्क नम्बर पुष्टि गर्नुहोस्।",
    "bring_documents": "भेटका लागि चाहिने कागजात र सामान पुष्टि गर्नुहोस्।"
  },
  "urdu": {
    "language_instruction": "براہ کرم وہ زبان منتخب کریں جو آپ سمجھتے ہیں۔",
    "reception": "استقبالیہ",
    "reception1": "استقبالیہ",
    "waiting_room": "اتاق انتظار",
    "consultation_room": "اتاق معاینه",
    "first_time": "کیا یہ آپ کا پہلا دورہ ہے؟",
    "yes": "ہاں",
    "no": "نہیں",
    "yes1": "ہاں",
    "no1": "نہیں",
    "self": "Have you taken a pregnancy test by yourself? Yes / No",
    "visit_reason": "لطفاً دلیل مراجعه امروز را انتخاب کنید.",
    "absence_period": "عادت ماهانه قطع شده است",
    "nausea": "حالت تهوع",
    "possible_pregnancy": "ممکن است باردار باشم",
    "inconsistent_period": "عادت ماهانه منظم نیست",
    "period_pain": "هنگام عادت ماهانه درد شکم دارم",
    "itching": "خارش در ناحیه بیرونی تناسلی",
    "stomach_pain": "درد شکم",
    "infertility_question": "می‌خواهم درباره ناباروری بپرسم",
    "other": "دیگر",
    "question": "طبی سوالنامہ",
    "fill_form_waiting_room": "لطفاً فورم صحی را در اتاق انتظار پر کنید.",
    "finished_filling_form": "پس از تکمیل، لطفاً آن را بیاورید.",
    "take_weight": "پیش از معاینه، وزن و فشار خون را اندازه بگیرید و آزمایش ادرار بدهید.",
    "weit_here": "لطفاً تا زمان معاینه در محل تعیین‌شده منتظر بمانید.",
    "staff_notification": "کارمند راهنمایی می‌کند کجا بروید.",
    "call_order": "به ترتیب نام یا شماره صدا زده می‌شوید.",
    "call_order2": "ترتیب ممکن است بسته به وضعیت تغییر کند.",
    "medicines": "دوا",
    "give_medicines_in_hospital": "دوا پس از معاینه در داخل شفاخانه داده می‌شود.",
    "give_medicines_out_of_hospital": "ممکن است لازم باشد دوا را از دواخانه بیرون شفاخانه بخرید.",
    "prescription_validity": "نسخه از روز صدور به شمول همان روز ۴ روز اعتبار دارد.",
    "payment_instructions_machine": "لطفاً در دستگاه پرداخت خودکار پرداخت کنید.",
    "payment_instructions_cashier": "لطفاً در صندوق پرداخت کنید.",
    "card": "کارت معاینه به شما داده می‌شود. از مراجعه بعدی آن را نشان دهید.",
    "system_information_detail": "جزئیات معلومات سیستم",
    "system_information_detail_link": "دیدن جزئیات معلومات سیستم",
    "notify_pregnancy_office": "لطفاً مراحل اطلاع‌دهی بارداری را در شاروالی محل زندگی خود تأیید کنید.",
    "mother_child_handbook": "لطفاً دفترچه سلامت مادر و کودک را دریافت کنید.",
    "checkup_tickets": "لطفاً طریقه استفاده از برگه‌های معاینه بارداری و کوپن‌های کمک را تأیید کنید.",
    "hospital_reservation": "شفاخانه یا کلینیک زایمان را زود انتخاب و رزرو کنید.",
    "insurance_payment": "بیمه صحی و روش پرداخت هزینه زایمان را تأیید کنید.",
    "financial_support": "کمک‌های مالی مانند کمک‌هزینه زایمان را تأیید کنید.",
    "municipal_support": "می‌توانید از خدمات مشاوره و حمایت شاروالی استفاده کنید.",
    "interpreter_support": "اگر به ترجمان یا مشاوره چندزبانه نیاز دارید، بگویید.",
    "emergency_contact_info": "شماره تماس شب و روزهای رخصتی را تأیید کنید.",
    "bring_documents": "اسناد و وسایل لازم برای مراجعه را تأیید کنید."
  }
};
