// Language and shared state
// Split from blood_sugar/index.html. Loaded as a classic script.

const currentPage = "blood_sugar";
/** @type {import('@line/liff').Liff} */
const liff = window.liff;

const sugarI18n = i18next.createInstance();
const LANG_STORAGE_KEY = "sugar_ui_lang";
const LANGUAGE_OPTIONS = [
  {
    code: "soft",
    label: "やさしい日本語",
  },
  {
    code: "en-US",
    label: "英語編(English)",
  },
  {
    code: "zh",
    label: "中国語編(中文版)",
  },
  {
    code: "fr",
    label: "フランス語編(French)",
  },
  {
    code: "ko",
    label: "韓国語編(Korean)",
  },
  {
    code: "pr",
    label: "ポルトガル語編(Portugues)",
  },
  {
    code: "tl",
    label: "タガログ語編(TAGALOG)",
  },
  {
    code: "ve",
    label: "ベトナム語編(Vietnam)",
  },
  {
    code: "th",
    label: "タイ語編(Thai)",
  },
  {
    code: "de",
    label: "ドイツ語編(German)",
  },
  {
    code: "id",
    label: "インドネシア語(Indonesia)",
  },
  {
    code: "ru",
    label: "ロシア語(Russian)",
  },
  {
    code: "ne",
    label: "ネパール語(Nepali)",
  },
  {
    code: "lo",
    label: "ラオス語(Laotian)",
  },
  {
    code: "uk",
    label: "ウクライナ語(Ukrainian)",
  },
  {
    code: "fa-AF",
    label: "ダリ語(Dari)",
  },
  {
    code: "si",
    label: "シンハラ語(Sinhala)",
  },
  {
    code: "ms",
    label: "マレー語(Malay)",
  },
  {
    code: "my",
    label: "ミャンマー語(Myanmar)",
  },
  {
    code: "bn",
    label: "ベンガル語(Bengali)",
  },
  {
    code: "ur",
    label: "ウルドゥー語(Urdu)",
  },
];
const UI_TEXT = {
  ja: {
    title: "血糖記録",
    settings: "設定",
    settingsTitle: "設定",
    language: "言語設定",
    close: "閉じる",
    date: "日付",
    period: "時間",
    periodCol: "時間帯",
    sugar: "血糖",
    sugarLabel: "血糖値 (mg/dL)",
    medication: "投薬",
    medicationNone: "なし",
    medicationYes: "あり",
    medicationUnit: "単位",
    targetNote: "目標: 食前 95mg/dL未満、食後 140mg/dL未満",
    add: "データを追加",
    older: "以前の情報をみる",
    noMore: "これ以上ありません",
    loading: "読み込み中...",
    register: "登録",
    chart: "グラフ",
    table: "テーブル",
    edit: "編集",
    save: "保存",
    cancel: "キャンセル",
    del: "削除",
    fillAll: "すべてのフィールドに値を入力してください。",
    beforeBreakfast: "朝食前",
    afterBreakfast: "朝食後",
    beforeLunch: "昼食前",
    afterLunch: "昼食後",
    beforeDinner: "夕食前",
    afterDinner: "夕食後",
    beforeSleep: "就寝前",
    yAxis: "血糖値 (mg/dL)",
    xAxis: "日付と時間帯",
  },
  soft: {
    title: "けっとうの きろく",
    settings: "せってい",
    settingsTitle: "せってい",
    language: "ことばを えらぶ",
    close: "とじる",
    date: "ひづけ",
    period: "じかん",
    periodCol: "じかんたい",
    sugar: "けっとう",
    sugarLabel: "けっとう (mg/dL)",
    medication: "くすり",
    medicationNone: "なし",
    medicationYes: "あり",
    medicationUnit: "たんい",
    targetNote: "めやす: ごはんの まえ 95mg/dLより ひくく、ごはんの あと 140mg/dLより ひくく",
    add: "データを いれる",
    older: "まえの きろくを みる",
    noMore: "これより まえの きろくは ありません",
    loading: "よみこんでいます...",
    register: "とうろく",
    chart: "グラフ",
    table: "ひょう",
    edit: "なおす",
    save: "ほぞん",
    cancel: "やめる",
    del: "けす",
    fillAll: "ぜんぶ いれてください。",
    beforeBreakfast: "あさごはんの まえ",
    afterBreakfast: "あさごはんの あと",
    beforeLunch: "ひるごはんの まえ",
    afterLunch: "ひるごはんの あと",
    beforeDinner: "よるごはんの まえ",
    afterDinner: "よるごはんの あと",
    beforeSleep: "ねる まえ",
    yAxis: "けっとう (mg/dL)",
    xAxis: "ひづけと じかんたい",
  },
  "en-US": {
    title: "Blood Sugar Tracker",
    settings: "Settings",
    settingsTitle: "Settings",
    language: "Language",
    close: "Close",
    date: "Date",
    period: "Time",
    periodCol: "Timing",
    sugar: "Blood Sugar",
    sugarLabel: "Blood Sugar (mg/dL)",
    medication: "Medication",
    medicationNone: "None",
    medicationYes: "Yes",
    medicationUnit: "Units",
    targetNote: "Target: under 95 mg/dL before meals, under 140 mg/dL after meals",
    add: "Add Data",
    older: "Show Older Data",
    noMore: "No More Data",
    loading: "Loading...",
    register: "Register",
    chart: "Chart",
    table: "Table",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    del: "Delete",
    fillAll: "Please fill all fields.",
    beforeBreakfast: "Before Breakfast",
    afterBreakfast: "After Breakfast",
    beforeLunch: "Before Lunch",
    afterLunch: "After Lunch",
    beforeDinner: "Before Dinner",
    afterDinner: "After Dinner",
    beforeSleep: "Before Sleep",
    yAxis: "Blood Sugar (mg/dL)",
    xAxis: "Date / Timing",
  },
  zh: {
    title: "血糖记录",
    settings: "设置",
    settingsTitle: "设置",
    language: "语言设置",
    close: "关闭",
    date: "日期",
    period: "时间",
    periodCol: "时段",
    sugar: "血糖",
    sugarLabel: "血糖值 (mg/dL)",
    medication: "投药",
    medicationNone: "无",
    medicationYes: "有",
    medicationUnit: "单位",
    targetNote: "目标: 餐前低于95 mg/dL，餐后低于140 mg/dL",
    add: "添加数据",
    older: "查看更早信息",
    noMore: "没有更多了",
    loading: "读取中...",
    register: "登记",
    chart: "图表",
    table: "表格",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    del: "删除",
    fillAll: "请填写所有项目。",
    beforeBreakfast: "早餐前",
    afterBreakfast: "早餐后",
    beforeLunch: "午餐前",
    afterLunch: "午餐后",
    beforeDinner: "晚餐前",
    afterDinner: "晚餐后",
    beforeSleep: "睡前",
    yAxis: "血糖值 (mg/dL)",
    xAxis: "日期 / 时段",
  },
  fr: {
    title: "Suivi de la glycémie",
    settings: "Paramètres",
    settingsTitle: "Paramètres",
    language: "Langue",
    close: "Fermer",
    date: "Date",
    period: "Heure",
    periodCol: "Moment",
    sugar: "Glycémie",
    sugarLabel: "Glycémie (mg/dL)",
    medication: "Médicament",
    medicationNone: "Aucun",
    medicationYes: "Oui",
    medicationUnit: "Unités",
    targetNote: "Objectif: moins de 95 mg/dL avant les repas, moins de 140 mg/dL après les repas",
    add: "Ajouter des données",
    older: "Voir les données précédentes",
    noMore: "Aucune autre donnée",
    loading: "Chargement...",
    register: "Enregistrer",
    chart: "Graphique",
    table: "Tableau",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    del: "Supprimer",
    fillAll: "Veuillez remplir tous les champs.",
    beforeBreakfast: "Avant le petit-déjeuner",
    afterBreakfast: "Après le petit-déjeuner",
    beforeLunch: "Avant le déjeuner",
    afterLunch: "Après le déjeuner",
    beforeDinner: "Avant le dîner",
    afterDinner: "Après le dîner",
    beforeSleep: "Avant de dormir",
    yAxis: "Glycémie (mg/dL)",
    xAxis: "Date / Moment",
  },
  ko: {
    title: "혈당 기록",
    settings: "설정",
    settingsTitle: "설정",
    language: "언어 설정",
    close: "닫기",
    date: "날짜",
    period: "시간",
    periodCol: "시간대",
    sugar: "혈당",
    sugarLabel: "혈당 (mg/dL)",
    medication: "투약",
    medicationNone: "없음",
    medicationYes: "있음",
    medicationUnit: "단위",
    targetNote: "목표: 식전 95 mg/dL 미만, 식후 140 mg/dL 미만",
    add: "데이터 추가",
    older: "이전 정보 보기",
    noMore: "더 이상 데이터가 없습니다",
    loading: "불러오는 중...",
    register: "등록",
    chart: "그래프",
    table: "테이블",
    edit: "편집",
    save: "저장",
    cancel: "취소",
    del: "삭제",
    fillAll: "모든 항목을 입력하세요.",
    beforeBreakfast: "아침 식전",
    afterBreakfast: "아침 식후",
    beforeLunch: "점심 식전",
    afterLunch: "점심 식후",
    beforeDinner: "저녁 식전",
    afterDinner: "저녁 식후",
    beforeSleep: "취침 전",
    yAxis: "혈당 (mg/dL)",
    xAxis: "날짜 / 시간대",
  },
  de: {
    title: "Blutzuckerprotokoll",
    settings: "Einstellungen",
    settingsTitle: "Einstellungen",
    language: "Sprache",
    close: "Schließen",
    date: "Datum",
    period: "Zeit",
    periodCol: "Zeitfenster",
    sugar: "Blutzucker",
    sugarLabel: "Blutzucker (mg/dL)",
    medication: "Medikamente",
    medicationNone: "Keine",
    medicationYes: "Ja",
    medicationUnit: "Einheiten",
    targetNote: "Ziel: vor Mahlzeiten unter 95 mg/dL, nach Mahlzeiten unter 140 mg/dL",
    add: "Daten hinzufügen",
    older: "Ältere Daten anzeigen",
    noMore: "Keine weiteren Daten",
    loading: "Wird geladen...",
    register: "Registrieren",
    chart: "Diagramm",
    table: "Tabelle",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    del: "Löschen",
    fillAll: "Bitte alle Felder ausfüllen.",
    beforeBreakfast: "Vor dem Frühstück",
    afterBreakfast: "Nach dem Frühstück",
    beforeLunch: "Vor dem Mittagessen",
    afterLunch: "Nach dem Mittagessen",
    beforeDinner: "Vor dem Abendessen",
    afterDinner: "Nach dem Abendessen",
    beforeSleep: "Vor dem Schlafen",
    yAxis: "Blutzucker (mg/dL)",
    xAxis: "Datum / Zeit",
  },
  pr: {
    title: "Registro de glicemia",
    settings: "Configurações",
    settingsTitle: "Configurações",
    language: "Idioma",
    close: "Fechar",
    date: "Data",
    period: "Horário",
    periodCol: "Período",
    sugar: "Glicemia",
    sugarLabel: "Glicemia (mg/dL)",
    medication: "Medicação",
    medicationNone: "Nenhuma",
    medicationYes: "Sim",
    medicationUnit: "Unidades",
    targetNote: "Meta: antes das refeições abaixo de 95 mg/dL, após as refeições abaixo de 140 mg/dL",
    add: "Adicionar dados",
    older: "Ver dados anteriores",
    noMore: "Não há mais dados",
    loading: "Carregando...",
    register: "Registrar",
    chart: "Gráfico",
    table: "Tabela",
    edit: "Editar",
    save: "Salvar",
    cancel: "Cancelar",
    del: "Excluir",
    fillAll: "Preencha todos os campos.",
    beforeBreakfast: "Antes do café da manhã",
    afterBreakfast: "Depois do café da manhã",
    beforeLunch: "Antes do almoço",
    afterLunch: "Depois do almoço",
    beforeDinner: "Antes do jantar",
    afterDinner: "Depois do jantar",
    beforeSleep: "Antes de dormir",
    yAxis: "Glicemia (mg/dL)",
    xAxis: "Data / Horário",
  },
  ve: {
    title: "Theo dõi đường huyết",
    settings: "Cài đặt",
    settingsTitle: "Cài đặt",
    language: "Ngôn ngữ",
    close: "Đóng",
    date: "Ngày",
    period: "Thời gian",
    periodCol: "Khung giờ",
    sugar: "Đường huyết",
    sugarLabel: "Đường huyết (mg/dL)",
    medication: "Thuốc",
    medicationNone: "Không",
    medicationYes: "Có",
    medicationUnit: "Đơn vị",
    targetNote: "Mục tiêu: trước bữa ăn dưới 95 mg/dL, sau bữa ăn dưới 140 mg/dL",
    add: "Thêm dữ liệu",
    older: "Xem dữ liệu cũ hơn",
    noMore: "Không còn dữ liệu",
    loading: "Đang tải...",
    register: "Đăng ký",
    chart: "Biểu đồ",
    table: "Bảng",
    edit: "Chỉnh sửa",
    save: "Lưu",
    cancel: "Hủy",
    del: "Xóa",
    fillAll: "Vui lòng nhập đầy đủ.",
    beforeBreakfast: "Trước bữa sáng",
    afterBreakfast: "Sau bữa sáng",
    beforeLunch: "Trước bữa trưa",
    afterLunch: "Sau bữa trưa",
    beforeDinner: "Trước bữa tối",
    afterDinner: "Sau bữa tối",
    beforeSleep: "Trước khi ngủ",
    yAxis: "Đường huyết (mg/dL)",
    xAxis: "Ngày / Khung giờ",
  },
  tl: {
    title: "Talaan ng blood sugar",
    settings: "Mga setting",
    settingsTitle: "Mga setting",
    language: "Wika",
    close: "Isara",
    date: "Petsa",
    period: "Oras",
    periodCol: "Panahon",
    sugar: "Blood sugar",
    sugarLabel: "Blood sugar (mg/dL)",
    medication: "Gamot",
    medicationNone: "Wala",
    medicationYes: "Meron",
    medicationUnit: "Unit",
    targetNote: "Target: bago kumain mas mababa sa 95 mg/dL, pagkatapos kumain mas mababa sa 140 mg/dL",
    add: "Magdagdag ng datos",
    older: "Tingnan ang mas lumang datos",
    noMore: "Wala nang ibang datos",
    loading: "Naglo-load...",
    register: "Irehistro",
    chart: "Grap",
    table: "Talahanayan",
    edit: "I-edit",
    save: "I-save",
    cancel: "Kanselahin",
    del: "Burahin",
    fillAll: "Pakilagyan ang lahat ng field.",
    beforeBreakfast: "Bago mag-almusal",
    afterBreakfast: "Pagkatapos mag-almusal",
    beforeLunch: "Bago mag-tanghalian",
    afterLunch: "Pagkatapos mag-tanghalian",
    beforeDinner: "Bago mag-hapunan",
    afterDinner: "Pagkatapos mag-hapunan",
    beforeSleep: "Bago matulog",
    yAxis: "Blood sugar (mg/dL)",
    xAxis: "Petsa / Panahon",
  },
  th: {
    title: "บันทึกน้ำตาลในเลือด",
    settings: "การตั้งค่า",
    settingsTitle: "การตั้งค่า",
    language: "ภาษา",
    close: "ปิด",
    date: "วันที่",
    period: "เวลา",
    periodCol: "ช่วงเวลา",
    sugar: "น้ำตาลในเลือด",
    sugarLabel: "น้ำตาลในเลือด (mg/dL)",
    medication: "ยา",
    medicationNone: "ไม่มี",
    medicationYes: "มี",
    medicationUnit: "หน่วย",
    targetNote: "เป้าหมาย: ก่อนอาหารต่ำกว่า 95 mg/dL หลังอาหารต่ำกว่า 140 mg/dL",
    add: "เพิ่มข้อมูล",
    older: "ดูข้อมูลก่อนหน้า",
    noMore: "ไม่มีข้อมูลเพิ่มเติม",
    loading: "กำลังโหลด...",
    register: "ลงทะเบียน",
    chart: "กราฟ",
    table: "ตาราง",
    edit: "แก้ไข",
    save: "บันทึก",
    cancel: "ยกเลิก",
    del: "ลบ",
    fillAll: "กรุณากรอกข้อมูลให้ครบ",
    beforeBreakfast: "ก่อนอาหารเช้า",
    afterBreakfast: "หลังอาหารเช้า",
    beforeLunch: "ก่อนอาหารกลางวัน",
    afterLunch: "หลังอาหารกลางวัน",
    beforeDinner: "ก่อนอาหารเย็น",
    afterDinner: "หลังอาหารเย็น",
    beforeSleep: "ก่อนนอน",
    yAxis: "น้ำตาลในเลือด (mg/dL)",
    xAxis: "วันที่ / ช่วงเวลา",
  },
};
UI_TEXT.id = {
  ...UI_TEXT["en-US"],
  title: "Catatan gula darah",
  settings: "Pengaturan",
  settingsTitle: "Pengaturan",
  language: "Bahasa",
  close: "Tutup",
  date: "Tanggal",
  period: "Waktu",
  periodCol: "Periode",
  sugar: "Gula darah",
  sugarLabel: "Gula darah (mg/dL)",
  medication: "Obat",
  medicationNone: "Tidak ada",
  medicationYes: "Ada",
  medicationUnit: "Unit",
  targetNote: "Target: sebelum makan di bawah 95 mg/dL, setelah makan di bawah 140 mg/dL",
  add: "Tambah data",
  older: "Lihat data sebelumnya",
  noMore: "Tidak ada data lagi",
  loading: "Memuat...",
  register: "Daftar",
  chart: "Grafik",
  table: "Tabel",
  edit: "Edit",
  save: "Simpan",
  cancel: "Batal",
  del: "Hapus",
  fillAll: "Silakan isi semua kolom.",
  beforeBreakfast: "Sebelum sarapan",
  afterBreakfast: "Setelah sarapan",
  beforeLunch: "Sebelum makan siang",
  afterLunch: "Setelah makan siang",
  beforeDinner: "Sebelum makan malam",
  afterDinner: "Setelah makan malam",
  beforeSleep: "Sebelum tidur",
  yAxis: "Gula darah (mg/dL)",
  xAxis: "Tanggal / Periode",
};
UI_TEXT.ru = {
  ...UI_TEXT["en-US"],
  title: "Дневник сахара в крови",
  settings: "Настройки",
  settingsTitle: "Настройки",
  language: "Язык",
  close: "Закрыть",
  date: "Дата",
  period: "Время",
  periodCol: "Период",
  sugar: "Сахар в крови",
  sugarLabel: "Сахар в крови (mg/dL)",
  medication: "Лекарства",
  medicationNone: "Нет",
  medicationYes: "Да",
  medicationUnit: "Единицы",
  targetNote: "Цель: до еды ниже 95 mg/dL, после еды ниже 140 mg/dL",
  add: "Добавить данные",
  older: "Посмотреть предыдущие данные",
  noMore: "Больше данных нет",
  loading: "Загрузка...",
  register: "Зарегистрировать",
  chart: "График",
  table: "Таблица",
  edit: "Редактировать",
  save: "Сохранить",
  cancel: "Отмена",
  del: "Удалить",
  fillAll: "Пожалуйста, заполните все поля.",
  beforeBreakfast: "До завтрака",
  afterBreakfast: "После завтрака",
  beforeLunch: "До обеда",
  afterLunch: "После обеда",
  beforeDinner: "До ужина",
  afterDinner: "После ужина",
  beforeSleep: "Перед сном",
  yAxis: "Сахар в крови (mg/dL)",
  xAxis: "Дата / Период",
};
UI_TEXT.ne = {
  ...UI_TEXT["en-US"],
  title: "रगतको चिनी रेकर्ड",
  settings: "सेटिङ",
  settingsTitle: "सेटिङ",
  language: "भाषा",
  close: "बन्द",
  date: "मिति",
  period: "समय",
  periodCol: "समय भाग",
  sugar: "रगतको चिनी",
  sugarLabel: "रगतको चिनी (mg/dL)",
  medication: "औषधि",
  medicationNone: "छैन",
  medicationYes: "छ",
  medicationUnit: "एकाइ",
  targetNote: "लक्ष्य: खाना अघि 95 mg/dL भन्दा कम, खाना पछि 140 mg/dL भन्दा कम",
  add: "डाटा थप्नुहोस्",
  older: "पुरानो जानकारी हेर्नुहोस्",
  noMore: "थप जानकारी छैन",
  loading: "लोड हुँदैछ...",
  register: "दर्ता",
  chart: "ग्राफ",
  table: "तालिका",
  edit: "सम्पादन",
  save: "सेभ",
  cancel: "रद्द",
  del: "मेटाउनुहोस्",
  fillAll: "कृपया सबै फिल्ड भर्नुहोस्।",
  beforeBreakfast: "नास्ता अघि",
  afterBreakfast: "नास्ता पछि",
  beforeLunch: "दिउँसोको खाना अघि",
  afterLunch: "दिउँसोको खाना पछि",
  beforeDinner: "बेलुकाको खाना अघि",
  afterDinner: "बेलुकाको खाना पछि",
  beforeSleep: "सुत्नु अघि",
  yAxis: "रगतको चिनी (mg/dL)",
  xAxis: "मिति / समय",
};
UI_TEXT.lo = {
  ...UI_TEXT["en-US"],
  title: "ບັນທຶກນ້ຳຕານໃນເລືອດ",
  settings: "ຕັ້ງຄ່າ",
  settingsTitle: "ຕັ້ງຄ່າ",
  language: "ພາສາ",
  close: "ປິດ",
  date: "ວັນທີ",
  period: "ເວລາ",
  periodCol: "ຊ່ວງເວລາ",
  sugar: "ນ້ຳຕານໃນເລືອດ",
  sugarLabel: "ນ້ຳຕານໃນເລືອດ (mg/dL)",
  medication: "ຢາ",
  medicationNone: "ບໍ່ມີ",
  medicationYes: "ມີ",
  medicationUnit: "ຫົວໜ່ວຍ",
  targetNote: "ເປົ້າໝາຍ: ກ່ອນອາຫານຕ່ຳກວ່າ 95 mg/dL, ຫຼັງອາຫານຕ່ຳກວ່າ 140 mg/dL",
  add: "ເພີ່ມຂໍ້ມູນ",
  older: "ເບິ່ງຂໍ້ມູນກ່ອນໜ້າ",
  noMore: "ບໍ່ມີຂໍ້ມູນເພີ່ມແລ້ວ",
  loading: "ກຳລັງໂຫຼດ...",
  register: "ລົງທະບຽນ",
  chart: "ກຣາບ",
  table: "ຕາຕະລາງ",
  edit: "ແກ້ໄຂ",
  save: "ບັນທຶກ",
  cancel: "ຍົກເລີກ",
  del: "ລົບ",
  fillAll: "ກະລຸນາປ້ອນຂໍ້ມູນໃຫ້ຄົບ.",
  beforeBreakfast: "ກ່ອນອາຫານເຊົ້າ",
  afterBreakfast: "ຫຼັງອາຫານເຊົ້າ",
  beforeLunch: "ກ່ອນອາຫານທ່ຽງ",
  afterLunch: "ຫຼັງອາຫານທ່ຽງ",
  beforeDinner: "ກ່ອນອາຫານແລງ",
  afterDinner: "ຫຼັງອາຫານແລງ",
  beforeSleep: "ກ່ອນນອນ",
  yAxis: "ນ້ຳຕານໃນເລືອດ (mg/dL)",
  xAxis: "ວັນທີ / ຊ່ວງເວລາ",
};
UI_TEXT.uk = {
  ...UI_TEXT["en-US"],
  title: "Запис рівня цукру в крові",
  settings: "Налаштування",
  settingsTitle: "Налаштування",
  language: "Мова",
  close: "Закрити",
  date: "Дата",
  period: "Час",
  periodCol: "Період",
  sugar: "Цукор у крові",
  sugarLabel: "Цукор у крові (mg/dL)",
  medication: "Ліки",
  medicationNone: "Немає",
  medicationYes: "Є",
  medicationUnit: "Одиниці",
  targetNote: "Ціль: до їжі нижче 95 mg/dL, після їжі нижче 140 mg/dL",
  add: "Додати дані",
  older: "Переглянути попередні дані",
  noMore: "Більше даних немає",
  loading: "Завантаження...",
  register: "Зареєструвати",
  chart: "Графік",
  table: "Таблиця",
  edit: "Редагувати",
  save: "Зберегти",
  cancel: "Скасувати",
  del: "Видалити",
  fillAll: "Будь ласка, заповніть усі поля.",
  beforeBreakfast: "До сніданку",
  afterBreakfast: "Після сніданку",
  beforeLunch: "До обіду",
  afterLunch: "Після обіду",
  beforeDinner: "До вечері",
  afterDinner: "Після вечері",
  beforeSleep: "Перед сном",
  yAxis: "Цукор у крові (mg/dL)",
  xAxis: "Дата / Період",
};
UI_TEXT["fa-AF"] = {
  ...UI_TEXT["en-US"],
  title: "ثبت قند خون",
  settings: "تنظیمات",
  settingsTitle: "تنظیمات",
  language: "زبان",
  close: "بستن",
  date: "تاریخ",
  period: "زمان",
  periodCol: "بازه",
  sugar: "قند خون",
  sugarLabel: "قند خون (mg/dL)",
  medication: "دوا",
  medicationNone: "ندارد",
  medicationYes: "دارد",
  medicationUnit: "واحد",
  targetNote: "هدف: پیش از غذا کمتر از 95 mg/dL، پس از غذا کمتر از 140 mg/dL",
  add: "افزودن داده",
  older: "دیدن معلومات قبلی",
  noMore: "معلومات بیشتری وجود ندارد",
  loading: "در حال بارگذاری...",
  register: "ثبت",
  chart: "نمودار",
  table: "جدول",
  edit: "ویرایش",
  save: "ذخیره",
  cancel: "لغو",
  del: "حذف",
  fillAll: "لطفاً همه بخش‌ها را پر کنید.",
  beforeBreakfast: "پیش از صبحانه",
  afterBreakfast: "پس از صبحانه",
  beforeLunch: "پیش از چاشت",
  afterLunch: "پس از چاشت",
  beforeDinner: "پیش از شام",
  afterDinner: "پس از شام",
  beforeSleep: "پیش از خواب",
  yAxis: "قند خون (mg/dL)",
  xAxis: "تاریخ / بازه",
};
UI_TEXT.si = {
  ...UI_TEXT["en-US"],
  title: "රුධිර සීනි සටහන",
  settings: "සැකසුම්",
  settingsTitle: "සැකසුම්",
  language: "භාෂාව",
  close: "වසන්න",
  date: "දිනය",
  period: "වේලාව",
  periodCol: "කාල පරාසය",
  sugar: "රුධිර සීනි",
  sugarLabel: "රුධිර සීනි (mg/dL)",
  medication: "ඖෂධ",
  medicationNone: "නැත",
  medicationYes: "ඇත",
  medicationUnit: "ඒකක",
  targetNote: "ඉලක්කය: ආහාරයට පෙර 95 mg/dL ට අඩු, ආහාරයෙන් පසු 140 mg/dL ට අඩු",
  add: "දත්ත එක් කරන්න",
  older: "පෙර තොරතුරු බලන්න",
  noMore: "තවත් දත්ත නොමැත",
  loading: "පූරණය වෙමින්...",
  register: "ලියාපදිංචි කරන්න",
  chart: "ප්‍රස්තාරය",
  table: "වගුව",
  edit: "සංස්කරණය",
  save: "සුරකින්න",
  cancel: "අවලංගු",
  del: "මකන්න",
  fillAll: "කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න.",
  beforeBreakfast: "උදෑසන ආහාරයට පෙර",
  afterBreakfast: "උදෑසන ආහාරයෙන් පසු",
  beforeLunch: "දවල් ආහාරයට පෙර",
  afterLunch: "දවල් ආහාරයෙන් පසු",
  beforeDinner: "රාත්‍රී ආහාරයට පෙර",
  afterDinner: "රාත්‍රී ආහාරයෙන් පසු",
  beforeSleep: "නිදාගැනීමට පෙර",
  yAxis: "රුධිර සීනි (mg/dL)",
  xAxis: "දිනය / කාල පරාසය",
};
UI_TEXT.ms = {
  ...UI_TEXT["en-US"],
  title: "Rekod gula darah",
  settings: "Tetapan",
  settingsTitle: "Tetapan",
  language: "Bahasa",
  close: "Tutup",
  date: "Tarikh",
  period: "Masa",
  periodCol: "Tempoh",
  sugar: "Gula darah",
  sugarLabel: "Gula darah (mg/dL)",
  medication: "Ubat",
  medicationNone: "Tiada",
  medicationYes: "Ada",
  medicationUnit: "Unit",
  targetNote: "Sasaran: sebelum makan bawah 95 mg/dL, selepas makan bawah 140 mg/dL",
  add: "Tambah data",
  older: "Lihat data terdahulu",
  noMore: "Tiada lagi data",
  loading: "Memuatkan...",
  register: "Daftar",
  chart: "Graf",
  table: "Jadual",
  edit: "Sunting",
  save: "Simpan",
  cancel: "Batal",
  del: "Padam",
  fillAll: "Sila isi semua medan.",
  beforeBreakfast: "Sebelum sarapan",
  afterBreakfast: "Selepas sarapan",
  beforeLunch: "Sebelum makan tengah hari",
  afterLunch: "Selepas makan tengah hari",
  beforeDinner: "Sebelum makan malam",
  afterDinner: "Selepas makan malam",
  beforeSleep: "Sebelum tidur",
  yAxis: "Gula darah (mg/dL)",
  xAxis: "Tarikh / Tempoh",
};
UI_TEXT.my = {
  ...UI_TEXT["en-US"],
  title: "သွေးတွင်းသကြား မှတ်တမ်း",
  settings: "ဆက်တင်",
  settingsTitle: "ဆက်တင်",
  language: "ဘာသာစကား",
  close: "ပိတ်ရန်",
  date: "ရက်စွဲ",
  period: "အချိန်",
  periodCol: "အချိန်ပိုင်း",
  sugar: "သွေးတွင်းသကြား",
  sugarLabel: "သွေးတွင်းသကြား (mg/dL)",
  medication: "ဆေး",
  medicationNone: "မရှိ",
  medicationYes: "ရှိ",
  medicationUnit: "ယူနစ်",
  targetNote: "ပစ်မှတ်: အစာမစားမီ 95 mg/dL အောက်၊ အစာစားပြီးနောက် 140 mg/dL အောက်",
  add: "ဒေတာထည့်ရန်",
  older: "ယခင်အချက်အလက်ကို ကြည့်ရန်",
  noMore: "နောက်ထပ်အချက်အလက် မရှိပါ",
  loading: "ဖွင့်နေသည်...",
  register: "စာရင်းသွင်းရန်",
  chart: "ဂရပ်",
  table: "ဇယား",
  edit: "ပြင်ဆင်ရန်",
  save: "သိမ်းရန်",
  cancel: "ပယ်ဖျက်",
  del: "ဖျက်ရန်",
  fillAll: "ကျေးဇူးပြု၍ အကွက်အားလုံးဖြည့်ပါ။",
  beforeBreakfast: "မနက်စာမစားမီ",
  afterBreakfast: "မနက်စာစားပြီးနောက်",
  beforeLunch: "နေ့လယ်စာမစားမီ",
  afterLunch: "နေ့လယ်စာစားပြီးနောက်",
  beforeDinner: "ညစာမစားမီ",
  afterDinner: "ညစာစားပြီးနောက်",
  beforeSleep: "အိပ်ရာဝင်မီ",
  yAxis: "သွေးတွင်းသကြား (mg/dL)",
  xAxis: "ရက်စွဲ / အချိန်ပိုင်း",
};
UI_TEXT.bn = {
  ...UI_TEXT["en-US"],
  title: "রক্তে শর্করার রেকর্ড",
  settings: "সেটিংস",
  settingsTitle: "সেটিংস",
  language: "ভাষা",
  close: "বন্ধ",
  date: "তারিখ",
  period: "সময়",
  periodCol: "সময়কাল",
  sugar: "রক্তে শর্করা",
  sugarLabel: "রক্তে শর্করা (mg/dL)",
  medication: "ওষুধ",
  medicationNone: "নেই",
  medicationYes: "আছে",
  medicationUnit: "ইউনিট",
  targetNote: "লক্ষ্য: খাবারের আগে 95 mg/dL এর কম, খাবারের পরে 140 mg/dL এর কম",
  add: "ডাটা যোগ করুন",
  older: "আগের তথ্য দেখুন",
  noMore: "আর কোনো তথ্য নেই",
  loading: "লোড হচ্ছে...",
  register: "নিবন্ধন",
  chart: "গ্রাফ",
  table: "টেবিল",
  edit: "সম্পাদনা",
  save: "সংরক্ষণ",
  cancel: "বাতিল",
  del: "মুছুন",
  fillAll: "সব ঘর পূরণ করুন।",
  beforeBreakfast: "সকালের খাবারের আগে",
  afterBreakfast: "সকালের খাবারের পরে",
  beforeLunch: "দুপুরের খাবারের আগে",
  afterLunch: "দুপুরের খাবারের পরে",
  beforeDinner: "রাতের খাবারের আগে",
  afterDinner: "রাতের খাবারের পরে",
  beforeSleep: "ঘুমানোর আগে",
  yAxis: "রক্তে শর্করা (mg/dL)",
  xAxis: "তারিখ / সময়কাল",
};
UI_TEXT.ur = {
  ...UI_TEXT["en-US"],
  title: "بلڈ شوگر ریکارڈ",
  settings: "ترتیبات",
  settingsTitle: "ترتیبات",
  language: "زبان",
  close: "بند کریں",
  date: "تاریخ",
  period: "وقت",
  periodCol: "دورانیہ",
  sugar: "بلڈ شوگر",
  sugarLabel: "بلڈ شوگر (mg/dL)",
  medication: "دوا",
  medicationNone: "نہیں",
  medicationYes: "ہاں",
  medicationUnit: "یونٹ",
  targetNote: "ہدف: کھانے سے پہلے 95 mg/dL سے کم، کھانے کے بعد 140 mg/dL سے کم",
  add: "ڈیٹا شامل کریں",
  older: "پچھلی معلومات دیکھیں",
  noMore: "مزید معلومات نہیں ہیں",
  loading: "لوڈ ہو رہا ہے...",
  register: "رجسٹر",
  chart: "گراف",
  table: "ٹیبل",
  edit: "ترمیم",
  save: "محفوظ کریں",
  cancel: "منسوخ",
  del: "حذف",
  fillAll: "براہ کرم تمام خانے پُر کریں۔",
  beforeBreakfast: "ناشتے سے پہلے",
  afterBreakfast: "ناشتے کے بعد",
  beforeLunch: "دوپہر کے کھانے سے پہلے",
  afterLunch: "دوپہر کے کھانے کے بعد",
  beforeDinner: "رات کے کھانے سے پہلے",
  afterDinner: "رات کے کھانے کے بعد",
  beforeSleep: "سونے سے پہلے",
  yAxis: "بلڈ شوگر (mg/dL)",
  xAxis: "تاریخ / دورانیہ",
};
let allData = [];
let token = "";
let userId = "";
let selectedUiLang = "en-US";
let sugarPage = 1;
let loadedWeekPages = 1;
let hasOlderSugar = true;
let loadingOlderSugar = false;
let chartInstances = [];
let currentRow1 = null;
let currentItemId = "";
let before_dateValue = "";
let before_periodValue = 0;
let bloodSugarChart = null;
let sugarI18nReady = Promise.resolve();
 function resolveI18nLang(langCode) {
  if (langCode === "ja") return "ja";
  if (langCode === "zh") return "zh";
  return "en-US";
}
 async function initI18n(langCode) {
  await sugarI18n.use(i18nextHttpBackend).init({
    lng: resolveI18nLang(langCode),
    fallbackLng: "ja",
    ns: ["translation"],
    defaultNS: "translation",
    load: "currentOnly",
    backend: {
      loadPath: "./i18n/{{lng}}.json",
    },
    interpolation: {
      escapeValue: false,
    },
  });
}
function tx(key, langCode = selectedUiLang) {
  const table =
    UI_TEXT[langCode] || UI_TEXT[resolveI18nLang(langCode)] || UI_TEXT.ja;
  if (table && Object.prototype.hasOwnProperty.call(table, key)) {
    return table[key];
  }
  const code = langCode === "ja" ? "ja" : resolveI18nLang(langCode);
  try {
    return sugarI18n.getFixedT(code, "translation")(key);
  } catch (e) {
    return (UI_TEXT.ja && UI_TEXT.ja[key]) || "";
  }
}
 function bt(key) {
  return tx(key, selectedUiLang) || tx(key, "ja") || key;
}
 function normalizeLangToUi(lang) {
  const raw = String(lang || "ja").toLowerCase();
  if (raw === "soft" || raw.startsWith("easy") || raw.startsWith("simple")) return "soft";
  if (raw.startsWith("zh")) return "zh";
  if (raw.startsWith("fr")) return "fr";
  if (raw.startsWith("ko")) return "ko";
  if (raw.startsWith("pt")) return "pr";
  if (raw.startsWith("tl")) return "tl";
  if (raw.startsWith("vi")) return "ve";
  if (raw.startsWith("th")) return "th";
  if (raw.startsWith("de")) return "de";
  if (raw.startsWith("id")) return "id";
  if (raw.startsWith("ru")) return "ru";
  if (raw.startsWith("ne")) return "ne";
  if (raw.startsWith("lo")) return "lo";
  if (raw.startsWith("uk")) return "uk";
  if (raw.startsWith("fa") || raw.startsWith("prs")) return "fa-AF";
  if (raw.startsWith("si")) return "si";
  if (raw.startsWith("ms")) return "ms";
  if (raw.startsWith("my")) return "my";
  if (raw.startsWith("bn")) return "bn";
  if (raw.startsWith("ur")) return "ur";
  if (raw.startsWith("ja")) return "ja";
  return "en-US";
}
 function isSupportedLang(code) {
  return (
    code === "ja" || LANGUAGE_OPTIONS.some((item) => item.code === code)
  );
}

function applyI18n() {
  const setText = (id, text) => {
    const el = document.getElementById(id);
    if (el) el.textContent = text;
  };
  setText("titleBs", bt("title"));
  setText("openAddFormBtn", bt("add"));
  setText("labelDate", bt("date"));
  setText("labelPeriod", bt("period"));
  setText("labelSugar", bt("sugar"));
  setText("labelMedication", bt("medication"));
  setText("medicationNoneLabel", bt("medicationNone"));
  setText("medicationYesLabel", bt("medicationYes"));
  setText("labelMedicationUnit", bt("medicationUnit"));
  setText("sugarTargetNote", bt("targetNote"));
  setText("adddata", bt("register"));
  setText("closeAddFormBtn", bt("cancel"));
  setText("thDate", bt("date"));
  setText("thPeriod", bt("periodCol"));
  setText("thSugar", bt("sugar"));
  setText("thMedication", bt("medication"));
  setText("ethDate", bt("date"));
  setText("ethPeriod", bt("periodCol"));
  setText("ethSugar", bt("sugar"));
  setText("ethMedication", bt("medication"));
  setText("ethEdit", bt("edit"));
  setText("editDateLabel", bt("date"));
  setText("editPeriodLabel", bt("period"));
  setText("editSugarLabel", bt("sugar"));
  setText("editMedicationLabel", bt("medication"));
  setText("editMedicationNoneLabel", bt("medicationNone"));
  setText("editMedicationYesLabel", bt("medicationYes"));
  setText("editMedicationUnitLabel", bt("medicationUnit"));
  setText("saveButton", bt("save"));
  setText("cancelButton", bt("cancel"));
  setText("deleteButton", bt("del"));
  setText("tabChart", bt("chart"));
  setText("tabTable", bt("table"));
  setText("tabEdit", bt("edit"));
  setText("periodBeforeBreakfast", bt("beforeBreakfast"));
  setText("periodAfterBreakfast", bt("afterBreakfast"));
  setText("periodBeforeLunch", bt("beforeLunch"));
  setText("periodAfterLunch", bt("afterLunch"));
  setText("periodBeforeDinner", bt("beforeDinner"));
  setText("periodAfterDinner", bt("afterDinner"));
  setText("periodBeforeSleep", bt("beforeSleep"));
  setText("editPeriodBeforeBreakfast", bt("beforeBreakfast"));
  setText("editPeriodAfterBreakfast", bt("afterBreakfast"));
  setText("editPeriodBeforeLunch", bt("beforeLunch"));
  setText("editPeriodAfterLunch", bt("afterLunch"));
  setText("editPeriodBeforeDinner", bt("beforeDinner"));
  setText("editPeriodAfterDinner", bt("afterDinner"));
  setText("editPeriodBeforeSleep", bt("beforeSleep"));
  if (bloodSugarChart) {
    bloodSugarChart.data.datasets[0].label = bt("sugarLabel");
    bloodSugarChart.options.scales.y.title.text = bt("yAxis");
    bloodSugarChart.options.scales.x.title.text = bt("xAxis");
  }
  syncOlderButtons();
  updateChartRangeTitle();
}
 async function setLanguage(langCode) {
  selectedUiLang = isSupportedLang(langCode) ? langCode : "en-US";
  localStorage.setItem(LANG_STORAGE_KEY, selectedUiLang);
  await sugarI18n.changeLanguage(resolveI18nLang(selectedUiLang));
  applyI18n();
  updateChart(allData);
  createTablePage();
  populateTable();
}
